### ISSUE TITLE
Collections lacking usage examples

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#100]
> It may also contain data files, executable resources like JavaScript, iPython scripts, or Java. 

The above sentence is not reflected in the usage examples.

**Comment by iherman** [comment]
True, something got lost. One of the primary examples (eg, for iPython) is scholarly publishing, which increasingly tries to include 'active' entities (data presentation, iPython scripts, etc) as an integral part of a scholarly paper.

@TzviyaSiegman do you have a good use case text for this from the top of your head?

**Comment by TzviyaSiegman** [comment]
We can use http://derivatives-analytics-with-python.com/ as an example.

**Comment by iherman** [comment]
You mean that 

> All Python codes (scripts, modules, etc. — a total of over 5,000 lines of codes) 

should be part of a PWP? Yep, that is a good example...

**Comment by lrosenthol** [comment]
Rewrote this entire section in the [branch](https://github.com/w3c/dpub-pwp-ucr/tree/dedupe), so that it properly reflects what we want from collections (multiple publications) rather than about resources (which have their own section).

**Comment by TzviyaSiegman** [comment]
Clarified and simplified in new draft.
