### ISSUE TITLE
Lisa use case could be improved...

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#103]
Maybe?: 

> A class of students is reading a book in which poems are pictorially presented in different shapes. To have a comparable experience as her sighted classmates, Lisa, who is visually impaired, needs access to the material in braille or auditory form.

**Comment by marcoscaceres** [comment]
The above is from 2.8 Multimedia PWPs

**Comment by iherman** [comment]
I would be happy to add [Marcos' use case](https://github.com/w3c/dpub-pwp-ucr/issues/103#issue-176800917).

@clapierre, would you agree?

**Comment by clapierre** [comment]
sure sounds good.

**Comment by iherman** [comment]
Proposed Solution: Add [Marcos' use case](https://github.com/w3c/dpub-pwp-ucr/issues/103#issue-176800917) to 2.8.

@hlflanagan

**Comment by avneeshsingh** [comment]
The use case is to emphasize the need of pre-formatted Braille, which is different than the dynamic Braile that is used for reading web pages. Addition of audio may reduce emphasis on Braille.

**Comment by marcoscaceres** [comment]
I don't see why braille should be more prominent than auditory form - both modalities work as effectively as each other AFAIK.

**Comment by marcoscaceres** [comment]
Put differently, they are not mutually exclusive.

**Comment by avneeshsingh** [comment]
Braille can be the replica of the print book, by using proper formatting i.e. one can perceive the same effect by using fingers. The visual appeal can be replicated into touch. But when we move to audio, it gets into something very different i.e. explanations using verbal descriptions, which gets into guidelines for audio descriptions.

**Comment by marcoscaceres** [comment]
Ok, but the point of the use case is that it can be in multiple modalities. I don't want us to get caught up on the details, as it really doesn't matter. What matters is if a useful requirement can emerge from the use cases.

**Comment by iherman** [comment]
I think we are indeed digressing a bit. Clearly Braille is important, clearly other modalities are important. At this time, the section (on Multimedia PWP) has 5 use cases, 3 out of those is on Braille. This is an imbalance. We have a possible reformulation in issue #102, a proposed reformulation for the one on Nemeth Braille (issue #101). I would propose
1. leave the Lisa use case more or less as is, addressing Braille only
2. have a _separate_ use case describing the fact that some blind readers prefer using audio

I also wonder whether the title is clear enough. We are talking about _alternate renditions_ of the PWP content, the emphasis being on _alternate_ (ie, not reading text only) and not on multimedia. For me, the term multimedia rather means that a 'traditional' text is enriched with graphics, video, audio, etc, which is of course important but is widely available on the Web already, ie, PWP does not bring anything different. The importance in this case is that, say, the same content should be available both in traditional persons who read the books whereas the _same_ content may need other media for other persons.

@clapierre @deborahgu ?

**Comment by hlflanagan** [comment]
For the title, how about "alternative media"? I'm still not sure I understand the nuances between "rendition" and "version".

**Comment by iherman** [comment]
"Version", for me, would be more about the content being different, whereas "rendition" is more about the same content being presented in different ways. But these may be minute details...

**Comment by marcoscaceres** [comment]
> "Version", for me, would be more about the content being different, whereas "rendition" is more about the same content being presented in different ways. But these may be minute details...

Agree. No, the use of "version" can indeed be confusing. I support going with "rendition" or "modalities".
