### ISSUE TITLE
Olga's dyslexia 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#104]
> Olga, a dyslexic student, downloads a textbook and proceeds to personalize the material with larger font and different contrast.

As a "dyslexic student" myself, I would say Olga would probably be using text-to-speech to access the text. Adjusting font sizes, etc doesn't help as much as text-to-speech.

**Comment by iherman** [comment]
@clapierre ?

**Comment by pkra** [comment]
Switching to a custom/specialized font might also be a worthwhile addition.

**Comment by marcoscaceres** [comment]
@pkra, sure - I can only comment from personal experience: fonts, sizes, colors, etc. doesn't help in my experience; but text-to-speech actually does because it overcomes the visual aspects of dyslexia.

**Comment by TzviyaSiegman** [comment]
This was written by someone based on her own experience. Your dyslexia might be different from hers. /cc @deborahgu

**Comment by clapierre** [comment]
There is a lot of contraversy on whether or not a dyslexic font really helps with reading and comprehension, but since there is a specific font named a dyslexic font which was researched and helped certain cases I believe this is still a valid statement.

**Comment by pkra** [comment]
@clapierre thanks! I was not aware of that.

**Comment by iherman** [comment]
@clapierre @deborahgu @marcoscaceres : would that work for all of you guys?

> Olga, a dyslexic student, downloads a textbook and proceeds to personalize the material with larger and/or a specialized dyslexic font, as well as different contrast which, for her particular case, makes the text easier to consume.

As an aside, this discussion just re-emphasizes how important it is to provide personalization:-)

**Comment by marcoscaceres** [comment]
s/different contrast which/different contrast that/

Otherwise, WFM.

**Comment by iherman** [comment]
Proposed solution: see https://github.com/w3c/dpub-pwp-ucr/issues/104#issuecomment-247289965 (with the minor change of Marcos)

**Comment by iherman** [comment]
Done in the [separate editorial branch](https://github.com/w3c/dpub-pwp-ucr/blob/pwp-ucr-editorial1/index.html).
