### ISSUE TITLE
Switching to dark mode...

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#105]
> When reading a book in the sun, Fanta adjusts the background color to a dark color so that she can see the text.

This example is incorrect. You would switch to background color white for contrast, not dark. The example should be:

> When reading a book in bed, Fanta adjusts the background color to a dark color so that she can see the text (and to not disturb her partner, who is trying to sleep). 

And Fanta? I hope there is an example with someone named Pepsi :)

**Comment by marcoscaceres** [comment]
Also, this example can probably go:

> Mia choses to read in night mode because she finds it easier to sleep when she puts the PWP aside.

It doesn't make much sense.

**Comment by iherman** [comment]
:-) :-) We used some program generating names that has already created some funny side effects, this is one of those:-)

@hlflanagan probably worth changing it to another name...

**Comment by iherman** [comment]
Yes, I agree that color scheme choice is incorrect. I would propose to change the text of the original use case by setting the background colour to, e.g., white (and keep the example with Mia)

**Comment by hlflanagan** [comment]
I'm changing the name to "Mia" as suggested. Regarding night mode and sleep, we should probably explain what night mode is (having the darker screen to avoid blue light in the eyes). It does help with sleep issues.

**Comment by marcoscaceres** [comment]
> I'm changing the name to "Mia" as suggested. Regarding night mode and sleep, we should probably explain what night mode is (having the darker screen to avoid blue light in the eyes). It does help with sleep issues.

No need to go overboard here. Remember this is just simple examples to justify the requirements. If we need to get too science about it, we are going to waste time. We've all seen this stuff in different apps - we don't need to convince people that it's of value.

**Comment by iherman** [comment]
Done in the [separate editorial branch](https://github.com/w3c/dpub-pwp-ucr/blob/pwp-ucr-editorial1/index.html).
