### ISSUE TITLE
2.10 Discoverability

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#106]
The example doesn't actually say how Frank, the ornithologist, actually discovers the publication.

**Comment by marcoscaceres** [comment]
(presumedly, you mean by installation into some kind of "library" or via a search engine?)

**Comment by lrosenthol** [comment]
Removed this section from the [branch](https://github.com/w3c/dpub-pwp-ucr/tree/dedupe)

**Comment by iherman** [comment]
It is now in the main branch; closing the issue
