### ISSUE TITLE
2.13 Access Control and Write Protections

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#108]
> A library may loan the publication for two weeks; the PWP should provide means for its environment to control the period of the loan.

This is backwards. It's up to the application to control its access control, not for some DRM scheme to be included (which this is eluding to!).

**Comment by marcoscaceres** [comment]
> She asks Bob to review the paper, but needs to make sure that the PWP retains specific protections, regardless of whether it is read online or offline.

The above is too ambiguous - what "specific protections"?

**Comment by sideshowbarker** [comment]
We already have long-standing existing standard features in the Web platform for limiting access of Web resources to authenticated users. The class of publications this document seems to be trying to address are no different in that regard than the billions of existing Web resources that are already being served on the Web using some form of access control. So there’s no need to explicitly state any requirements about “protections” or anything similar in this document.

If this requirement is here to attempt to address what might happen with resources off the Web, outside of the Web runtime, then I think it should not be trying to do that. We are here to develop new technologies for the Web runtime. And it is already possible—has always been possible—for someone to take an HTML document off the Web into some other environment, and we have never (yet) tried to define technologies that place any restrictions on what somebody can do with an HTML document outside of the Web runtime. And we should not.

**Comment by mac2net** [comment]
Yes exactly! As the DIGIPUB group knows this is exactly the solution I am advocating and I call it 5DOC and the group has also seen numerous examples of my concept of online/offline abstraction.
And yet this idea - offline HTML via a file URL which has existed since 1994 - remains unaddressed in all documents tech specs, etc as if it doesn't exist.

**Comment by marcoscaceres** [comment]
@mac2net, let's finish the review and formalizing the use cases and requirements - we've talked about file:// before, so let's return to that when we do "possible solutions".

**Comment by mac2net** [comment]
OK, but I hope at that point there will be a full discussion.
I am worried because, like I perviously mentioned, this already working alternative is inexplicably never mentioned even as a "strawman". For example in the upcoming PWP slides - http://w3c.github.io/dpub/IDPC-2016/index.html#38.

**Comment by lrosenthol** [comment]
@sideshowbarker Actually one of the key drivers for PWP **IS** to provide a framework for "taking HTML documents off the web" (aka offline).  That doesn't necessarily mean taking them into "another environment", though it might.

**Comment by marcoscaceres** [comment]
@mac2net, those slides are @iherman's opinion (not invalid or anything! - but don't represent consensus, because we are still going through this discovery phase).

**Comment by marcoscaceres** [comment]
> That doesn't necessarily mean taking them into "another environment", though it might.

You can't really take HTML off "the web", because the security model and features depend on the same origin policy. If that is not there, all things break lose and it stops working properly.

**Comment by pkra** [comment]
> You can't really take HTML off "the web", because the security model and features depend on the same origin policy. If that is not there, all things break lose and it stops working properly.

Personally I think more of "move around" (i.e., portable). In particular as an author, I want to allow users to "move" their instance of a PWP on their own; I don't mind if that requires a host somewhere (e.g., a "reading app" that runs a webserver).

**Comment by lrosenthol** [comment]
> You can't really take HTML off "the web", because the security model and features depend on the same origin policy. If that is not there, all things break lose and it stops working properly.

That's simply not true.  Consider HTML Email, which has been around for close to 20 years now.  That is HTML that is not on the web.  And it works properly.

I agree, however, that the same origin policy is a key aspect for the development of PWP - where the origin for such is either the hosting site OR the package in which it is contained.  (and as @pkra  said, it could be moved around)

**Comment by marcoscaceres** [comment]
> That's simply not true. Consider HTML Email, which has been around for close to 20 years now. That is HTML that is not on the web. And it works properly.

I'm afraid it doesn't: For security reasons, email clients discard parsing scripts in HTML email, as they have been continuously used to launch [security and privacy attacks](https://en.wikipedia.org/wiki/HTML_email#Security_vulnerabilities). 

> I agree, however, that the same origin policy is a key aspect for the development of PWP - where the origin for such is either the hosting site OR the package in which it is contained. (and as @pkra said, it could be moved around).

Again, it's not a given that a package is needed - specially if it can be shown that all the requirements can be met just using plain old HTTPS origins, without any sort of packaging container.

**Comment by lrosenthol** [comment]
@marcoscaceres Not sure what email client(s) you use, but many clients out there support execution of scripts.  (granted, it may require user action, just as it does with "download images", but that's still an option)

I am still waiting for you to provide us with a solution to the ad-hoc distribution problem that does not require a package.  When you can do that, I'll be all ears for removing that requirement.  Until then, it remains.

**Comment by baldurbjarnason** [comment]
> @marcoscaceres Not sure what email client(s) you use, but many clients out there support execution of scripts. (granted, it may require user action, just as it does with "download images", but that's still an option)

Based on the research I've done, this is not true. No actively maintained email app that I found supports javascript in received emails. Certainly none of the big ones. Many _do_ support javascript in  templates but not in received emails. Some of them _do_ support various active content (gifs, CSS animation, SVG, etc) but not javascript.  Some of them will run JS if you turn off or dial down the Windows OS-wide security features, but that's obviously not recommended. 

And HTML in email is by a large margin the least consistent and most convoluted platform available for web development. Many designers are still resorting to tables for layout due to the difficulty of delivering a consistent experience across email clients. It's a web development platform that's arrested in the late 90s/early 2000s. It is not a web development platform anybody should emulate. Using HTML email as a role model or precedent is a non-starter.

**Comment by lrosenthol** [comment]
Back on the original topic, I rewrote the section in my [branch](https://github.com/w3c/dpub-pwp-ucr/tree/dedupe) to use better terms about the PWP and the user agent.

**Comment by TzviyaSiegman** [comment]
Closing this issue because it was derailed in discussions of what "offline" means. Create new issue to discuss validity of http://w3c.github.io/dpub-pwp-ucr/index.html#access-control-and-write-protections if need be cc @marcoscaceres and @sideshowbarker
