### ISSUE TITLE
3.2 Single Unit

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#109]
> Req. 15: User agents must treat a PWP, regardless of the number of components, as a single unit as opposed to individual documents.

This view of the web is somewhat misguided (and possibly unattainable) - particularly for dynamically changing resources. Saying that it's a MUST is a non-starter IMO. 

> User agent must be able to search a complete PWP as one unit.

That resources be searchable was not itself a use case that was explored in section 2 - it should be added a use case.

**Comment by marcoscaceres** [comment]
> A user should be able to access all linear content through simple UI gestures, independent of the document structure.

This is often application dependent - not dependent on the user agent. Some texts may lend themselves to this, but some not.

**Comment by iherman** [comment]
This seems to be the same issue as #99. I propose to close this to concentrate the discussion in that issue.

@marcoscaceres ?
