### ISSUE TITLE
Use case review: Social reading and annotations 

### ISSUE THREAD

**Issue by rdeltour** [w3c/dpub-pwp-ucr#11]
> - 9. [Social Reading and Annotations](https://www.w3.org/dpub/IG/wiki/UseCase_Directory#Social_Reading_and_Annotations)
>   - 9.1. Use Cases Targeting Full Publication
>   - 9.2. Use Cases Targeting Specific Segments
>   - 9.3. Advanced Use Cases
>   - 9.4. Annotation Packages
>   - 9.5. Annotation Publication
>   - 9.6. Other Use Cases

Dozens of UCs. Are they in scope? I suppose most UC fall under the responsibility of the Web Annotation WG.

The PWP specific issues are:
- publication identifiers – which are likely out of scope
- URLs to publications or fragment therein
- portability of the annotations with the PWP
- PWP made of annotations

Depending on what is in scope for this document, we can consolidate a couple key use cases.

**Comment by iherman** [comment]
> On 29 Jan 2016, at 23:27, Romain Deltour notifications@github.com wrote:
> 1. Social Reading and Annotations https://www.w3.org/dpub/IG/wiki/UseCase_Directory#Social_Reading_and_Annotations
>    9.1. Use Cases Targeting Full Publication
>    9.2. Use Cases Targeting Specific Segments
>    9.3. Advanced Use Cases
>    9.4. Annotation Packages
>    9.5. Annotation Publication
>    9.6. Other Use Cases
>    Dozens of UCs. Are they in scope? I suppose most UC fall under the responsibility of the Web Annotation WG.
> 
> The PWP specific issues are:
> 
> publication identifiers – which are likely out of scope

See my comments on UC vs. being out of scope. It is a problem that _someone_ must solve, we just do not think it is W3C

> URLs to publications or fragment therein
> portability of the annotations with the PWP
> PWP made of annotations
> All are important categories, fully agree!
