### ISSUE TITLE
3.4 Default Reading Order

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#111]
> Req. 17: Find the (default) reading order of the resources of a PWP easily.

This takes a misguided view that it should be up to the UA to organize the information from a list of resources. This is wrong: it should be up to the application to best organize the information and present ways of getting to that information to the user.

**Comment by iherman** [comment]
Why? How can an application find the correct, or optimal, order of reading the chapters of a book out of a bunch of files in a directory on the Web? Some hints, some information must be made available.

**Comment by marcoscaceres** [comment]
The developer/author/publisher knows the correct reading order: they are in the best position to present that information as a ToC. However, it seems you are assuming that it would be the user agent that would present/generate some kind of ToC (it should would not do that).

**Comment by iherman** [comment]
@marcoscaceres yes. So it may be as simple as providing some sort of a standard ToC in some standard way, and make it clear how the user agent would find it. We never claimed anything else...

(In the current EPUB3 that role is played by a specific HTML5 file using a <nav> element marked in a certain way, and referred to from the publication's manifest. Nothing magic.)

**Comment by marcoscaceres** [comment]
> @marcoscaceres yes. So it may be as simple as providing some sort of a standard ToC in some standard way, and make it clear how the user agent would find it. We never claimed anything else...

No, forget the UA... the UA is not interested in finding or presenting a ToC to the user. That's not a requirement. The UA wants the developers to present a ToC to the user. 

> element marked in a certain way, and referred to from the publication's manifest. Nothing magic.

But that _is_ the definition of magic. That process of linking together a manifest, a HTML list of some sort, and then it appearing like the following is totally magic.

(attaching pic in next comment... can't seem to attach for some reason...)

**Comment by marcoscaceres** [comment]
This is magic (iBooks, ToC generation): 

![screenshot 2016-09-14 18 08 25](https://cloud.githubusercontent.com/assets/870154/18504620/9a8f3b46-7aa6-11e6-8fa8-8f6028083e41.png)

**Comment by iherman** [comment]
@marcoscaceres I am afraid:-) that we are in a violent agreement...

What you show is the ToC generated by (I believe) the iBook reader. The way it happens is based on what I said: the EPUB instance contains an html5 file with the ToC (using the `<nav>` element) and referred to by the manifest of the EPUB instance. This is the type of mechanism that, per requirement, should be available somehow in a PWP. That is all we are saying...

**Comment by marcoscaceres** [comment]
So, perhaps then: 

> Req. 17: a means of indicating the author-preferred navigation order of the resources of a PWP.

**Comment by marcoscaceres** [comment]
Maybe it's "navigation structure", because it's a tree

**Comment by iherman** [comment]
I am fine with that.

Proposed solution: use [Marcos' formulation](https://github.com/w3c/dpub-pwp-ucr/issues/111#issuecomment-246939928)

Cc: @hlflanagan

**Comment by BorisAnthony** [comment]
I think I am in disagreement.
Do not assume ToC are only ever in author-defined "story flow" and we should also not assume ToC are encoded in some strict data-format (this would unnecessarily straight jacket creators and consumer.)

Scenario:
My PWP includes 3 different ToCs: one in "story flow" structure (traditional author-defined ToC), one in pure chronological order, one in alphabetical order of characters (e.g. chapters are narrated by different characters and this order would allow reader to read in order of narrator).

p.s.: **These 3 ToCs could be marked up as HTML** rather than some unnecessarily over-engineered XML or JSON data structure, and ready to be presented. The UA simply needs a mechanism to display them separately from the contents.

**Comment by iherman** [comment]
@BorisAnthony I do not think we really are in a disagreement:-)

So far we discussed, in conjunction with Req 17, the simple case: when there _is_ a single default ToC (and, I believe, @marcoscaceres and I agreed on the term 'default navigation structure'). But is of course correct that, in some cases, a publication may have several different navigation structures associated to it. We decided to put that as a separate, non-fundamental requirement: [Req. 29](https://www.w3.org/TR/pwp-ucr/#r_manifest-reading). But the way these structures are expressed should follow a similar structure and the UA needs to provide some sort of a way for the user to choose among them.

**Comment by TzviyaSiegman** [comment]
No one is in disagreement. Everyone has said the same thing in different ways. The author/content preparer has a mechanism for defining sequence of content to be displayed to reader. Per @marcoscaceres, this can be as simple as `<nav>`. Per @BorisAnthony, author might have reason to give the reader multiple methods for navigating content, and this should be standardized. TOC and manifest might be interchangeable terms.

**Comment by dauwhe** [comment]
I have a bad habit of showing things in pre-Blink Opera, but it can display the TOC with only this magic:

`<a href="toc.html" rel="sidebar" title="Moby-Dick Table of Contents">`

<img width="600" alt="reading-e0-opera" src="https://cloud.githubusercontent.com/assets/5687700/18528830/903c7f5e-7a98-11e6-8628-7e5b67e32b28.png">

Long live the secondary browsing context! And declarative methods of doing common, simple things!

**Comment by iherman** [comment]
Done in the [separate editorial branch](https://github.com/w3c/dpub-pwp-ucr/blob/pwp-ucr-editorial1/index.html).
