### ISSUE TITLE
3.5 Uniquely Identifying a PWP

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#112]
> Req. 18: There should be a way to uniquely identify a publication regardless of its state.

This seems like a massive privacy issue. 

I have no words...

**Comment by lrosenthol** [comment]
@marcoscaceres how so?  Is it any different  from the existence of a URL for all "web resources"?

**Comment by TzviyaSiegman** [comment]
@marcoscaceres We need your words to respond.

**Comment by GarthConboy** [comment]
Is there an issue of with the meaning of "uniquely identify a publication"?  Not each instance of said publication.  I view this more like ISBN or URL.

**Comment by marcoscaceres** [comment]
@GarthConboy thanks for clarifying. ISBN or URL makes sense... I have words again :)

**Comment by dauwhe** [comment]
Perhaps it would be useful throughout the document to be clear when we are identifying a "manifestation" (in the FRBR sense) versus when we are identifying an exemplar of a manifestation, an "item."

**Comment by marcoscaceres** [comment]
I think that would be helpful. The idea of identifying a publication through existing means (e.g., ISBN) is kinda growing on me.
