### ISSUE TITLE
4. States of a PWP

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#113]
This whole section is misguided. Controlling network/offline access is irrelevant in a service worker world. You can mix and match based on business requirements: you can behave like offline, when online.. you can be offline, but first try to go to the network... you can handle some things offline, others not, etc.

**Comment by sideshowbarker** [comment]
I think the core issue with this section is that it seems to start from an implicit assumption that some sort of packaging format is necessary. So the section states no actual user use cases but instead one requirement (the one mentioned in https://github.com/w3c/dpub-pwp-ucr/issues/114) and otherwise just makes a number of assertions—the most problematic of which is “These different states require a different behavior from the user agent”.

If no packaging format is needed, then no different “states“ are required and no different behavior is needed from the UA with regard to those “states”.

If this document is to make any assumptions, it should (as @marcoscaceres alludes to in this issue)  assume the use of service workers—just as it already assumes the use of HTML and CSS.

Given that Service Workers [are intended to be a standard feature of the Web platform](https://www.w3.org/TR/service-workers/), just as HTML and CSS are, are already implemented in two major browser engines (Blink/Chrome and Gecko/Firefox) and are either already in development or under active consideration in the other two major browser engines (Edge and WebKit/Safari), it would be appropriate for this document to assume their use in the same way it already assumes the use of HTML and CSS.

And as @marcoscaceres points out in this issue, if the use of Service Workers is taken as a given, then other assumptions the “States of a PWP“ section is making become irrelevant—and the section can be removed entirely.

**Comment by lrosenthol** [comment]
@sideshowbarker It's much more than an assumption, but a **requirement** that there be a (at least one flavor of) packaged format for a PWP.

@marcoscaceres while service workers are good things, they are not a solution for all problems - and in fact, they don't address a number of requirements in the PWP world.  Also, some of the current SW limitations (eg. HTTPS only) would preclude various use cases we require for PWP.

**Comment by marcoscaceres** [comment]
> @sideshowbarker It's much more than an assumption, but a requirement that there be a (at least one flavor of) packaged format for a PWP.

Why? If we can show you don't need it, then you don't need it. 

> @marcoscaceres while service workers are good things, they are not a solution for all problems - and in fact, they don't address a number of requirements in the PWP world.

Like? 

> Also, some of the current SW limitations (eg. HTTPS only) would preclude various use cases we require for PWP.

Mozilla and Google have made it clear that we won't support new features unless they are HTTPS. This is a nonstarter for us, as implementers.

**Comment by lrosenthol** [comment]
> Why? If we can show you don't need it, then you don't need it.

Sure.  If you can demonstrate how to provide for ad-hoc (aka non-web-based) distribution of OWP content, such as via an eBook store or USB key, without the need for a package format - we're all ears!

> Mozilla and Google have made it clear that we won't support new features unless they are HTTPS. This is a nonstarter for us, as implementers.

Understood.  Which is why Service Workers are not a solution for all PWP needs.

**Comment by dauwhe** [comment]
@lrosenthol wrote:

> Sure. If you can demonstrate how to provide for ad-hoc (aka non-web-based) distribution of OWP content, such as via an eBook store or USB key, without the need for a package format - we're all ears!

Is "ad-hoc distribution" a fundamental requirement, or one possible way of meeting a more fundamental requirement? I know lots of us (including me!) sometimes suffer from epub-related cognitive bias. And emailing a file to a friend seems fundamental, but it is it the only way?

**Comment by lrosenthol** [comment]
> Is "ad-hoc distribution" a fundamental requirement

I won't presume to speak for everyone, but IMO, **yes**, ad-hoc distribution is a fundamental requirement for PWP.

> And emailing a file to a friend seems fundamental, but it is it the only way?

To me, at least, it's not about having a limited set of ways that distribution can happen - it's about allowing **any** means of distribution that the author of the content wishes to (or is able to) use.

**Comment by TzviyaSiegman** [comment]
Emailing a PWP to a friend could be emailing a link to a friend, not a file. It's still possible, just a different scenario.

**Comment by dauwhe** [comment]
> To me, at least, it's not about having a limited set of ways that distribution can happen - it's about allowing any means of distribution that the author of the content wishes to (or is able to) use.

While "baked into a pie" is a singularly wonderful distribution method, I don't see it as a high-priority use case ;)

**Comment by nruffilo** [comment]
Not every device will be online.  Imagine that a retailer has a device that gets publications either transfered via a USB cable, or through wifi, then the device is meant to be taken anywhere and used mainly offline.  Those are the situations in which online VS offline are considered.  Also - since this functionality of offline vs online will be used by nearly all publications, expecting that each publication would have to implement things themselves seems unnecessary.

There are lots of other situations - like children in a school where internet might be heavily restricted, and an "offline" version will be highly useful.

I guess to put things differently - this document outlines the use cases and needs.  There seems to be an assertion that there needs to be states - but really, it's just defining the use cases that a PWP will be used in a no-connectivity area and in connectivity situations, and certain functionality will be required - so if the web as it is today provides a solution for all these cases, great, if not, then a solution needs to be determined.

**Comment by marcoscaceres** [comment]
> Not every device will be online. Imagine that a retailer has a device that gets publications either transfered via a USB cable, or through wifi, then the device is meant to be taken anywhere and used mainly offline. Those are the situations in which online VS offline are considered.

Side-loading is extremely dangerous and error prone: it can be subject to all sorts of attacks and manipulation (e.g., file changed, replaced, etc). This is a none-starter as a use case or a requirement. 

>  Also - since this functionality of offline vs online will be used by nearly all publications, expecting that each publication would have to implement things themselves seems unnecessary.

I don't know what "each publication would have to implement things themselves" means. 

What things? 

> There are lots of other situations - like children in a school where internet might be heavily restricted, and an "offline" version will be highly useful.

We can't solve social problems with technology in this way (particularly with regards to net neutrality). However, if a person owns the device, they can go down the road and connect to a different wifi network. 

> I guess to put things differently - this document outlines the use cases and needs. There seems to be an assertion that there needs to be states - but really, it's just defining the use cases that a PWP will be used in a no-connectivity area and in connectivity situations, and certain functionality will be required - so if the web as it is today provides a solution for all these cases, great, if not, then a solution needs to be determined.

Yes, that's precisely what we are trying to get at.

**Comment by pkra** [comment]
> Side-loading is extremely dangerous and error prone: it can be subject to all sorts of attacks and manipulation (e.g., file changed, replaced, etc). 

This leaves me with a lot of FUD. This applies to anything "portable" yet people love to send around pdf, docx, epub, even html files with inline JS.

> This is a none-starter as a use case or a requirement.

This seems rather extreme. Rather, I suspect that if "portability" is resolved in some way, then this scenario can be resolved to some degree.

I've not be following the PWP development as closely as other DPUB members, so I consider myself relatively uninformed and the following side-comment will likely be too vague (and spans multiple issue discussions here).

One part of the discussion seems to run into trouble around notions of "on disk" and "copy something", "send something by email", which seem to me to have little to do with the question of portability.

It seems to me, that if a "website" can be "portable" in some way, then it can be transferred without network connectivity. Portability seems to includes a) transfer away from the origin b) transfer controlled by the user. The packaging seems to me to be an independent (hopefully irrelevant) question; whether a creator zips the files for transfer, whether the package is encrypted and maybe only trusted reading apps can decrypt it, whether a reading app enforces some form of protection on its output, all of that seems irrelevant to the question of portability. It's the files that count (whatever "files" they are). 

On a related note, another sticky point seem to be "offline/online". It seems to me to be a reasonable requirement, that a PWP is served from a web server (which, as Marco and Michael point out, makes the difference between "offline" and online" void under service workers [where only WebKit is holding out]). Expecting a "reading app" to run a (local) web server seems rather normal to me (iiuc, Readium already does that for serving files from an unzipped epub3 file within mobile apps).

I suppose websites "in their entirety" are already portable -- just transfer the entire server (though I'm sure there's an art project somewhere of a website that dies with its server infrastructure). Of course people usually don't allow users enough access to do that. So right now, users have things like copy&paste, html emails (oh the humanity), and epub-like things. It seems to me a (the?) point of PWP is to figure out how more advanced web"things" can be made portable.

My two cents anyway. Looking forward to next week.

**Comment by marcoscaceres** [comment]
> This leaves me with a lot of FUD. This applies to anything "portable" yet people love to send around pdf, docx, epub, even html files with inline JS.

Yes, and look at all the problems that happen with that. It's not FUD at all. Latest version of Word warns you if docx file has macros and tells you that you are potentially about to be hacked. Adobe Acrobat... where do we start. I already provided links about deprecation of `http://` wrt HTML files and email. Thankfully, HTML is pretty locked down in browsers (e.g., can't read disk, etc) - but a lot of attacks are initiated that way. 

> It seems to me, that if a "website" can be "portable" in some way, then it can be transferred without network connectivity. 

If you can send A to B over a medium, then that's network portability. Why that should not be the internet, using Web protocols, is the question. 

> Portability seems to includes a) transfer away from the origin b) transfer controlled by the user. The packaging seems to me to be an independent (hopefully irrelevant) question; whether a creator zips the files for transfer, whether the package is encrypted and maybe only trusted reading apps can decrypt it, whether a reading app enforces some form of protection on its output, all of that seems irrelevant to the question of portability. It's the files that count (whatever "files" they are).

On the Web, it's whatever is fetched and interpreted at a URL (i.e.., the resources loaded when you hit example.com). Those are not necessarily files. 

Anyway, I think we are getting a bit meta here. But the discussion has been very productive I think.

**Comment by rdeltour** [comment]
> If you can send A to B over a medium, then that's network portability. Why that should not be the internet, using Web protocols, is the question.

So here's a use case:

"Dave is reading Moby Dick on his tablet (at home with network connectivity). He then jumps on a plane with his good friend Tzviya. After having finished reading the book, he wants to lend it to Tzviya, so that she can start reading on her own tablet. They are both offline, but can exchange data with SD cards or Bluetooth."

Can the Web runtime and its protocols cover this use case already? (honest question).

**Comment by marcoscaceres** [comment]
> Can the Web runtime and its protocols cover this use case already? (honest question).

No. Not without a lot of contortions (like trying to hook up together over webRTC). Mozilla is currently working on something that would allow this: https://hacks.mozilla.org/2016/09/flyweb-pure-web-cross-device-interaction/

**Comment by rdeltour** [comment]
> Mozilla is currently working on something that would allow this: https://hacks.mozilla.org/2016/09/flyweb-pure-web-cross-device-interaction/

Interesting, thanks for the pointer! It seems that this involves streaming that requires a constant connection between both devices (I might be wrong, I had a very brief glance).  The use case here however is "definitely transfer content from one device to another when offline".
Maybe it's a no-go with the Web runtime, but I think that's a legit use case when dealing with consumable content like music, photos, and... publications.

**Comment by marcoscaceres** [comment]
> Interesting, thanks for the pointer! It seems that this involves streaming that requires a constant connection between both devices (I might be wrong, I had a very brief glance).

No, it's just a local web server that can be discovered by other devices nearby. 

> The use case here however is "definitely transfer content from one device to another when offline".

Yep, that's what it does. 

> Maybe it's a no-go with the Web runtime, but I think that's a legit use case when dealing with consumable content like music, photos, and... publications.

Yes, that's also the problem flyweb is trying to solve (and more).

**Comment by lrosenthol** [comment]
And what happens when Dave wants to send that to Tzviya who is not on the same plane?

And how does Tzviya now store a permanent copy of the book on a CD for future review?

**Comment by lrosenthol** [comment]
> persistence is a problem for the whole web, no? 

Yes.  However, it's a **key** requirement for PWP - our "little slice of the web".   And once we can get you to accept that - it will make our discussions easier. :)

**Comment by nruffilo** [comment]
A PWP lives in an interesting world.  While the goal is to have it built on web technologies, it is simultaneously ALSO a media type (possibly wrong wording here).  For example, take video or audio.  You can purchase a song (audio file) from a store, load it onto a device, share it (prevention of sharing is an addon that is a vendor thing, but worth noting here).  You can listen to that audio file if you are connected to the net or not.

Where PWP becomes unique - and where I feel states are a useful thing to discuss - is that a PWP - as with any website - could contain dynamic data.  An example, and I believe there is a use-case, would be scientific data.  A PWP about local temperature data, that is updated daily, would obviously want to load the most up-to-date external data file.  But, if offline, having the capability to say: "If offline, instead of loading someserver.com/mydata load localhost/data_as_of_publication" Localhost could be the PWP prefix, I'm not proposing semantics here.

So - having the concept of a container is basically saying: "what is necessary for this PWP to be 'complete' and what is ancillary"  It would be very useful for the PWP to be able to specify what items are required for offline, and what are not - and having to do this with service workers may not be the best/most logical solution (but I don't know enough yet to make a full assertion on this).  A PWP could say: "here are the chapters that are critical, but annotations are online-mode only" 

Also - imagine trying to make a PWP out of a Wikipedia article.  If you had to follow every link on a given page (and then THAT page's links) your PWP would be insanely huge.  But, if you could denote a link as "required for offline", you could extract just the article and maybe 1 or 2 others, leaving the rest as dynamic resources that only get loaded if internet is available.  

Also - mentioned elsewhere in the document - is archiving.  The web is dynamic, but a document should have the capability of being static.  Being able to say: "As of this date, the wording XYZ was written in this publication" is important for many reasons, so being able to create an "offline" or static version of a PWP that is stored locally is hugely important.  Think of the Library of Congress.

**Comment by iherman** [comment]
@nruffilo said:

> Also - mentioned elsewhere in the document - is archiving. [...] Think of the Library of Congress.

Actually… although archiving is a term usually referred to in relations to the LoC or their other national equivalents, I believe what may even be more relevant is what I would call "personal" archiving. And this also relates to @sideshowbarker's [comment](https://github.com/w3c/dpub-pwp-ucr/issues/107#issuecomment-247672761):

> As you note, users won’t use the word “package” or think in terms of it. Instead they think in terms of problems like “I want to be able to continue to read this Web book on my tablet even when I have no Internet connection.” And they can do that without needing to have the Web book packaged or made “portable” off the Web.

I believe, at least in my own, personal experience, that users want _more_ than just that. I have lots of physical books, and I also have a sizable amount of digital books. In many respect, I want many things from digital books that I am used to in the physical world, and that makes digital books different than just an average information page on the Web. I want to have my personal copy that I can give to may family at any time, regardless of where I am; I want to trust that I can read it in 3-4, nay, 20 years; I want to be able to leave it to my son when I am gone; I want to scribble on it and find those _personal_ and _private_ scribbles later easily just by opening the book, etc. There is a trust issue: just as I, frankly, do _not_ trust the vague "cloud" to (exclusively) hold all my music, and I store them on my own disc (and I actually duplicate or triplicate them to be sure), I must admit I have much more trust in having a physical copy of the book I bought on my personal disc(s) in a similar manner. Yes, I may be old, I may be out of touch, I may have some outdated view of what I expect from books, but I am sure I am not alone with these needs. Until I am 100% sure that I can trust a somewhat more volatile-looking, volatile-feeling technology, the more tangible things are the better is for me. As I said, it is also a matter of trust, and the "user" community of book readers is, I would think, more conservative. And it may well be that in, say, 10-15 years the situation will be different but I believe that _today_ we do need those personal, private, shall we say "off the Web" copies.

All that being said: I do recognize that many areas of publishing does _not_ require that. If I put on my researcher's hat on, I have no need for a similar level of archiving for a scholarly paper or even for a technical book. I do have technical digital books on my disc that I do not need any more, and I do not care about. But it is very different for some of the literary works that I cherish. So it may well be that the "packaged" version is a special thing and should be treated somewhat differently (maybe in a different 'profile', to be technical). But it cannot be dismissed as unnecessary or even harmful. We just have to find its right place in the overall landscape.

Sorry to be a bit verbose...

**Comment by mac2net** [comment]
Ivan, on the subject of the tactile digital experience, I made a 5DOC of your presentation for the upcoming Plenary meeting in Brussels. (updated link for downloading - https://www.sugarsync.com/pf/D0977460_090_700843556)

Please click on the red “5” to download the offline version. Sorry it loads a little slowly online (60MB with the encoded images) and the video is also loaded from the remote source for the offline version. The build and download time is similar to the build time for the PDF.

The 5DOC version can be loaded in any browser via the file URL. It can be zipped and emailed to a colleague for side-loading. And it could be stored on the W3C server for direct downloading.

BTW I think it looks pretty good. There are some slight differences in font metrics and one font-face inconsistency.

Along with Web, PDF and 5DOC formats of your presentation, I would like to see a service worker version of this or a least an estimation of when an SW version could be produced.

Cheers
Mike

**Comment by mac2net** [comment]
One of the images was crashing the base64 encoding for visitors who weren't logged in so I put a zipped version of the HTML file on sugarsync for downloading.
https://www.sugarsync.com/pf/D0977460_090_700843556

**Comment by mac2net** [comment]
I discovered that the source of the earlier problems was that video(s) - both formats - are actually encoded and included in the 5DOC (I thought encoding was off for the videos) which means the entire presentation can be viewed offline w/o an internet connection.

**Comment by mac2net** [comment]
There was a slight difference in the encoding Regex for <img> and <source>
I took out the OGG, left in the mp4 and kept encoding turned on.
The downloaded version including video works offline in Safari, Chrome and Firefox.
The presentation can be viewed and downloaded from here:
http://samples.5doc.org/content/slides-portable-web-publications-pwp/#1
The download size is approx 30mb, zipped 20mb.

**Comment by llemeurfr** [comment]
What I keep from this thread is that the possibility to store, share and side-load a PWP as a unique  file should be a clear requirement, where it is currently only a UC in "Distribution Process" (http://w3c.github.io/dpub-pwp-ucr/#pwp-process), i.e. the Ahmed use case.
This requirement would be illustrated with different use cases, like the ones listed in this thread, plus (important)
- X is blind, he is using a special e-reader that has no Internet connection, but can side-load files from an SD card (some of you must know about the Humanware Victor). Y loads a PWP for him on a SD card and shares it with X.

**Comment by marcoscaceres** [comment]
@nruffilo, regarding Wikipedia - check out the following in Chrome or Firefox: 
https://wiki-offline.jakearchibald.com

It illustrates many of the things you theorized above using service workers + wikipedia.

**Comment by marcoscaceres** [comment]
> I believe, at least in my own, personal experience, that users want more than just that. I have lots of physical books, and I also have a sizable amount of digital books. In many respect, I want many things from digital books that I am used to in the physical world, and that makes digital books different than just an average information page on the Web.

Again, I disagree. This applies to all the things on the Internet where a user feels ownership (e.g., I own 150 Steam Games - but not physical copies of them). I value and love them as much as any of my physical books. I also own 300+ books from audible.com, and love all of them - but the right to share them has long been taken away from me 😭. I traded that right for the ability to access them online, and have them available on multiple devices at once. 

I don't know if that's a good thing... but it's something I did. The same with my Spotify subscription: I don't own any music any more - and threw away my CDs (I don't know where I would even find a CD player these days!). I traded owning music for access to an ever growing catalogue of music, but gave up my right to own any of that music (shrug). Same with my Netflix subscription.  

Could be exactly the same with books... I have a Safari Books subscription, and I can access more technical knowledge than I could ever dream of. I know a lot people would trade physical books for this kinds of access any day of the week, rather than having physical books rotting away inside the house.... same with my subscription to the Economist (which I also love, because I get access to latest + the whole back catalogue... it's amazing! and no old paper magazines around the house).   

> I want to have my personal copy that I can give to may family at any time, regardless of where I am; I want to trust that I can read it in 3-4, nay, 20 years;

This assumes the paper won't break down. Or with other formats, like video tapes, that players for those formats will still be around in 20 years (this takes a romantic view of books). But sure, today, if you want those assurances, paper is your best bet because it doesn't depend on a viewer of some sort.  The trade off is, your paper book is kinda boring: it can't update itself, it can't read itself out-loud, it can't adjust its font, etc... all the magical things digital texts can do. And, being organic, it will eventually turn yellow and brittle and decompose.  

Point being: web content from 20 years ago is still accessible today. However, like depending on  physical paper to not decompose, on the web, we depend on servers/services being available. The web is built on open formats, chances are those texts will still be available in 20 years. 

> I want to be able to leave it to my son when I am gone; I want to scribble on it and find those personal and private scribbles later easily just by opening the book, etc. There is a trust issue: just as I, frankly, do not trust the vague "cloud" to (exclusively) hold all my music, and I store them on my own disc (and I actually duplicate or triplicate them to be sure), I must admit I have much more trust in having a physical copy of the book I bought on my personal disc(s) in a similar manner. Yes, I may be old, I may be out of touch, I may have some outdated view of what I expect from books, but I am sure I am not alone with these needs. 

Agree. Tradeoffs. 

> Until I am 100% sure that I can trust a somewhat more volatile-looking, volatile-feeling technology, the more tangible things are the better is for me. As I said, it is also a matter of trust, and the "user" community of book readers is, I would think, more conservative. And it may well be that in, say, 10-15 years the situation will be different but I believe that today we do need those personal, private, shall we say "off the Web" copies.

The explosion of services like Apple Music, Spotify, Netflix, etc. suggests that users don't mind renting media for the right price. It is also not "all or nothing" here. Dead-tree books are not going anywhere.

**Comment by lrosenthol** [comment]
I removed this entire section from my [branch](https://github.com/w3c/dpub-pwp-ucr/tree/dedupe) as it just causes too much confusion.  Online/Offline are handled elsewhere without reference to state.  In fact, there is no more "state" concept in that branch.

**Comment by iherman** [comment]
This is now in the same branch (after @lrosenthol's work). Closing the issue.
