### ISSUE TITLE
Retitle the document

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/dpub-pwp-ucr#118]
Many of the use cases and requirements both in this document and discussed in various issue comments such as https://github.com/w3c/dpub-pwp-ucr/issues/99#issuecomment-246954352 and https://github.com/w3c/dpub-pwp-ucr/issues/99#issuecomment-247121513 have nothing to do with “portability” or with distribution and especially nothing to do with packaging.

So the use of the term _Portable Web Publications_  gives the impressions of unnecessarily narrowing the scope of the document (and the overall DPUB effort behind it) to being very narrowly about just “portability” and distribution.

So I propose that we retitle the document to something less restrictive in scope.

As an example, consider something like “Web Document Collections: Use cases and requirements”.

**Comment by iherman** [comment]
Certainly to be discussed next week. Warning: this may become a rathole:-) (or bikeshedding...). But, maybe, with enough beers or equivalents around, we can find a better name

Cc: @TzviyaSiegman @GarthConboy

**Comment by lrosenthol** [comment]
@sideshowbarker And maybe what we really need are multiple efforts.  One that tackles some of the problems that are more "generic" to the web, and another that addresses the portability requirements.

**Comment by sideshowbarker** [comment]
> @sideshowbarker And maybe what we really need are multiple efforts. One that tackles some of the problems that are more "generic" to the web, and another that addresses the portability requirements.

Yes. I believe the group would be doing themselves a big favor by clearly splitting out the portability requirements in some way. I think that in order to get the most careful consideration of the requirements from browser-engine implementors (and so actually have some chance of getting things implemented), what the group will really need is for implementor attention to first be focused on the problems that you describe as more "generic" to the web.

**Comment by HadrienGardeur** [comment]
Web Document Collections sounds like a good name IMO.

I still believe that the main output will be a manifest format, so it could also be Web Publication Manifest or Web Document Manifest.

**Comment by TzviyaSiegman** [comment]
Document is now title (Packaged) Web Publications. Issue can be re-opened if this needs to be re-addressed.  cc/ @sideshowbarker
