### ISSUE TITLE
Up to the author, not the packaging software 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#119]
In section 5.5 External Data, it states:

> It is up to the packaging software to decide which resources will be included, and which will not. 

It should state that it's up to the author instead. Packaging software packages things, it doesn't make human decisions.

**Comment by marcoscaceres** [comment]
Additionally:

> but they decide to inactivate the inclusion of the research data in the packaged publication

Should drop the word "packaged".

**Comment by iherman** [comment]
Yes, that is a bug. Should be taken care of after the document is reorganized in terms of removing the reference to packaged publication. _At the moment_, a possible reformulation may be

> It is up to the author to decide which resources will be included, and which will not. This requirement adds the possibility to specify that some data must stay external to the Web Publication.

**Comment by lrosenthol** [comment]
I agree that we need to reformulate this BUT this si still primarily about
packages and not standard web publications.

**Comment by marcoscaceres** [comment]
> I agree that we need to reformulate this BUT this si still primarily about packages and not standard web publications.

I respectfully disagree. A HTML document includes `<img>, <script>, <link rel=stylesheet>` tags for the sole purpose of indicating that they are part of the publication.  

Similarly, using the Cache API, an author makes the decisions as to which files to make available for offline use, and which fetch requests should go to the network (and how to gracefully handle network failures, in case of offline).

**Comment by lrosenthol** [comment]
On Thu, Sep 29, 2016 at 3:35 AM, Marcos Cáceres notifications@github.com
wrote:

> I agree that we need to reformulate this BUT this si still primarily about
> packages and not standard web publications.
> 
> I respectfully disagree. A HTML document includes <img>, <script>, <link
> rel=stylesheet> tags for the sole purpose of indicating that they are
> part of the publication.
> 
> Similarly, using the Cache API, an author makes the decisions as to which
> files to make available for offline use, and which fetch requests should go
> to the network (and how gracefully handle network failures, in case of
> offline).
> 
> Yes, for Web Publications - I completely agree!

However, this particular use case was for the packaged case.  I'm working
to make the separation clearer in the document.

**Comment by iherman** [comment]
(Admin: some agreed editorial changes have been made in https://github.com/w3c/dpub-pwp-ucr/commit/f59fb82a7c8b8bd6ba122659baa3cb61058fa79b, but left the issue open because a more complete reformulation should come when the reorg is complete)

**Comment by lrosenthol** [comment]
All fixed in the latest drafts!
