### ISSUE TITLE
Use case review: Packaging and Distribution

### ISSUE THREAD

**Issue by rdeltour** [w3c/dpub-pwp-ucr#12]
> - 10. [Packaging and Distribution](https://www.w3.org/dpub/IG/wiki/UseCase_Directory#Packaging_and_Distribution)
- ["Publication with Data"](https://www.w3.org/dpub/IG/wiki/Publication_with_Date) is about declaring remote data source in the package.  
  **Evaluation**: to be consolidated, maybe with the following.
- ["Publication with Interactive Data"](https://www.w3.org/dpub/IG/wiki/Publication_with_Interactive_Data) is about using javascript in PWP (incl. calling remote services, package of libs embedded in package)  
  **Evaluation**: 
  - the "package in package" idea is interesting, but maybe out of scope for the first iteration?
  - the "call of remote services" idea s/b consolidated.
- ["Publication plus Annotations"](https://www.w3.org/dpub/IG/wiki/Publication_plus_Annotations) is about annotating a packaged PWP.  
  **Evaluation**: see Annotation use cases.
- ["Items with Shared Resources"](https://www.w3.org/dpub/IG/wiki/Items_with_Shared_Resources) is about PWP sharing common resources (e.g. Images, CSS, Javascript).  
  **Evaluation** the use case is in scope but s/b clarified, notably to specify what "shared resources" mean in packaged/unpackaged, where they are located, etc.
- ["Streamlined Access to Disjoint Package Components"](https://www.w3.org/dpub/IG/wiki/Streamlined_Access_to_Disjoint_Package_Components) is about providing "samples" of a PWP (e.g. abstract, toc).  
  **Evaluation**: probably in scope, but the relation of this "sample view" of a PWP and the original PWP must be clarified (built-in? spin-off using shared resource? totally independent publication?)
- ["Manifest Includes Information about New Content"](https://www.w3.org/dpub/IG/wiki/Manifest_Includes_Information_about_New_Content) is about updating an existing PWP with new content.  
  **Evaluation** in scope, to be consolidated.
- ["Overview of OCF Functionality"](https://www.w3.org/dpub/IG/wiki/OCF_Functionality) is not really a UC but describes some OCF-specific features.  
  **Evaluation** some features may be integrated in use cases, if deemed in scope or important. E.g. magic numbers, encryption, signatures, obfuscation.
- ["Access Control and selective encryption"](https://www.w3.org/dpub/IG/wiki/Access_Control_and_selective_encryption) is mostly about DRM.  
  **Evaluation** are DRM in scope? see also #14.
- ["Functional Requirements"]() is not a UC but instead lists some requirements. It will be a useful resource to see if we have good use case coverage.

We must also decide on which features are in scope, e.g.:
- streamability
- package-in-package (packages all the way down!)
- updateability
- sharing/using the same package among multiple users
- ease of packaging/unpackaging with existing tools

We also lack use cases related to the relation between the packaged/unpackaed states (transitioning between each other, link resilience, etc).

**Comment by iherman** [comment]
> On 29 Jan 2016, at 23:30, Romain Deltour notifications@github.com wrote:
> 1. Packaging and Distribution https://www.w3.org/dpub/IG/wiki/UseCase_Directory#Packaging_and_Distribution
>    "Publication with Data" https://www.w3.org/dpub/IG/wiki/Publication_with_Date is about declaring remote data source in the package.
>    Evaluation: to be consolidated, maybe with the following.
>    "Publication with Interactive Data" https://www.w3.org/dpub/IG/wiki/Publication_with_Interactive_Data is about using javascript in PWP (incl. calling remote services, package of libs embedded in package)
>    Evaluation:
>    the "package in package" idea is interesting, but maybe out of scope for the first iteration?
>    Keep it in the UC list.
> 
> the "call of remote services" idea s/b consolidated.
> "Publication plus Annotations" https://www.w3.org/dpub/IG/wiki/Publication_plus_Annotations is about annotating a packaged PWP.
> Evaluation: see Annotation use cases.
> "Items with Shared Resources" https://www.w3.org/dpub/IG/wiki/Items_with_Shared_Resources is about PWP sharing common resources (e.g. Images, CSS, Javascript).
> Evaluation the use case is in scope but s/b clarified, notably to specify what "shared resources" mean in packaged/unpackaged, where they are located, etc.
> "Streamlined Access to Disjoint Package Components" https://www.w3.org/dpub/IG/wiki/Streamlined_Access_to_Disjoint_Package_Components is about providing "samples" of a PWP (e.g. abstract, toc).
> Evaluation: probably in scope, but the relation of this "sample view" of a PWP and the original PWP must be clarified (built-in? spin-off using shared resource? totally independent publication?)
> "Manifest Includes Information about New Content" https://www.w3.org/dpub/IG/wiki/Manifest_Includes_Information_about_New_Content is about updating an existing PWP with new content.
> Evaluation in scope, to be consolidated.
> "Overview of OCF Functionality" https://www.w3.org/dpub/IG/wiki/OCF_Functionality is not really a UC but describes some OCF-specific features.
> Evaluation some features may be integrated in use cases, if deemed in scope or important. E.g. magic numbers, encryption, signatures, obfuscation.
> That page is less a UC but rather a description of the features of OCF today. What we should look at is section by section whether they are _really_ important as separate UC-s
> 
> "Access Control and selective encryption" https://www.w3.org/dpub/IG/wiki/Access_Control_and_selective_encryption is mostly about DRM.
> Evaluation are DRM in scope? see also #14.
> It is a UC all right, just not one everybody agrees with… I am not sure what to do with it. We cannot put our heads in the sand, so we may keep it as a UC but, separately, declare it out of bound for us.

We may want to try in describing DRM in more general way that allows other types of technologies (watermarking, etc) without being bound to one specific technology like current DRM.

> "Functional Requirements" applewebdata://59356905-95FE-4D95-B76E-96A680F40B6E is not a UC but instead lists some requirements. It will be a useful resource to see if we have good use case coverage.
> We must also decide on which features are in scope, e.g.:
> 
> streamability
> Probably. Although I remember Brady giving some examples where the streamability may become useless...
> package-in-package (packages all the way down!)
> updateability
> sharing/using the same package among multiple users
> ease of packaging/unpackaging with existing tools

All good ones!

**Comment by lrosenthol** [comment]
- Publication with Data (embedded, remote, interactive) is an important use case.  Perhaps it should get its own top level issue?
- Shared Resources also seems to be connecting to the workflows item.
- Disjoint components.  I don't understand this use case.  Do we have more info about it?
- Updatable PWP.  This seems to also conflict with the locators work since an updated PWP is a new PWP (but may be linked to the original?)
- OCF.  This is an implementation detail and not in scope at this time.
- DRM.  See the item about DRM for detals.

**Comment by rdeltour** [comment]
> Publication with Data (embedded, remote, interactive) is an important use case. Perhaps it should get its own top level issue?

Yes, probably. The purpose of this issue was to make a first pass of review on the old use cases from the wiki. Some of them are to be discarded, others merged one with another. Very few will be ported as is, if any.
At some point, I will have to consolidate the comments and propose a set of draft UC to be incorporated in the doc.

> Disjoint components. I don't understand this use case. Do we have more info about it?

As far as I understand, the issue is about distributing only part of a PWP. Or restricting access to part of it. E.g. a big retailer who wants to offer book previews.
There are several ways to look at it IMO:
- a "preview" is a totally different PWP, case closed.
- OR, it's a DRM issue.
- OR, we want a way to define a PWP as a subset of another PWP.

> Updatable PWP. This seems to also conflict with the locators work since an updated PWP is a new PWP (but may be linked to the original?)

Right.

> OCF. This is an implementation detail and not in scope at this time.

OCF is an implementation detail, but the functionality it enables are not. We need to decide if we want a UC for (resp.) encryption, signatures, font obfuscation, etc.

**Comment by lrosenthol** [comment]
> As far as I understand, the issue is about distributing only part of a PWP

Ah, I see.  This seems like something that has a big overlap with the locators work as if it is a "part" of some other PWP, you would probably want to be able to describe that relationship.

> We need to decide if we want a UC for (resp.) encryption, signatures, font obfuscation, etc.

Is encryption the same as DRM or not?  I see them as the same, and we have a DRM topic.

I think signatures are another topic that deserves a top level topic.

Font handling is, IMO, out of scope as it is a legal issue and not a file format concern.  We simply need to ensure that fonts can be included/referenced.
