### ISSUE TITLE
6.1 Manifests, Metadata, and Resources lacks use cases

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#123]
The usage example section of 6.1 Manifests, Metadata, and Resources needs to be rewritten as user-centered use cases.

**Comment by iherman** [comment]
Proposed solution:

> - The author should have the possibility to provide additional information on the Web Publication, like:
>   - captions belonging to multimedia resources within the publication;
>   - accessibility information on each component (see also "Accessible Metadata");
>   - the title, author(s), cover image, etc., to display the publication on a shelf without downloading all its content see also "Discoverability", "Accessible Metadata");
>   - whether the content is unaltered (see also "Security");
>   - the origin of the publication.

**Comment by GarthConboy** [comment]
s/on the publication/about the publication/

How do you view the, say, ONIX for a publication falling under the above bullets?

**Comment by iherman** [comment]
I would consider ONIX as a metadata _referred to_ from the "main" set of information ("manifest", with a caveat on the name), as opposed being included in that main set. Putting another way, it is a set of metadata whose format and content we cannot control...

**Comment by GarthConboy** [comment]
True though clearly, at least for some applications, sad will be the bulk of the "additional information about the Web Publication".  And, yes, referred to somehow.
