### ISSUE TITLE
6.2 Streamlining a PWP

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#124]
> Req. 26: Manifest should make it possible to provide a streamlined access to disjoint parts of the publication.

I don't see why a manifest would have anything at all to do with this. Sure, one could do this via a manifest, but that's the requirement is not dependent on a manifest.

**Comment by marcoscaceres** [comment]
In fact, the examples for this section show that this use case is not dependent on the manifest (or even any metadata) at all. 

Also "The App Package must..."? That's a new one :) But seriously, how the application manifests its ToC, etc. is application dependent and not dependent on "metadata".

**Comment by iherman** [comment]
> On 28 Sep 2016, at 03:52, Marcos Cáceres notifications@github.com wrote:
> 
> In fact, the examples for this section show that this use case is not dependent on the manifest (or even any metadata) at all.
> 
> Also "The App Package must..."? That's a new one :) But seriously, how the application manifests its ToC, etc. is application dependent and not dependent on "metadata".

First of all, we are back to the terminology issue; the use case do not say that it must be part of the manifest file itself. See also my remark on the usage of the term metadata… we have to agree on a neutral term.

The only thing this use case says is that there may be more than one ToC-s, and not only one default reading order, and it is up to the user to choose among those. I do not see the problem with that.

**Comment by marcoscaceres** [comment]
I feel like maybe ToC should be it's own section - with particular requirements. It keeps coming up a lot.

**Comment by lrosenthol** [comment]
Renamed the section "Random Access" and provided additional descriptions and use cases.

**Comment by TzviyaSiegman** [comment]
Revised in updated doc. See http://w3c.github.io/dpub-pwp-ucr/index.html#streamlining
