### ISSUE TITLE
6.3 Change Notices is not depedent on manifest

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#125]
> Req. 27: Manifest should include information of new content

This is, again, not dependent on a "manifest".  An author has an numerous ways of surfacing this information to users. In as far as authors can notify users of changes to publications is sufficient (independent of manifests).

**Comment by marcoscaceres** [comment]
Also, the usage example doesn't match the use case - and in fact, negates the use case. I would expect, "Chemistry App notifies Shoshana that the article she is reading has recieved an update, and prompts her if she would like to see the changes".

**Comment by iherman** [comment]
> On 28 Sep 2016, at 03:57, Marcos Cáceres notifications@github.com wrote:
> 
> Also, the usage example doesn't match the use case - and in fact, negates the use case. I would expect, "Chemistry App notifies Shoshana that the article she is reading has recieved an update, and prompts her if she would like to see the changes".

Yep, that is a bug.

Proposed Solution: replace the text with the version of Marcos.

**Comment by iherman** [comment]
(Admin: see https://github.com/w3c/dpub-pwp-ucr/commit/987403f486f4c6d2f2da85e2a051c11f03c8c712 for some of the changes made, but the terminology issue keeps this issue open)

**Comment by lrosenthol** [comment]
I removed this entire section as @marcoscaceres is correct that this isn't specific to PWP and in fact, I would argue, not even a good use case for us.

**Comment by iherman** [comment]
Per @lrosenthol's work, closing the issue
