### ISSUE TITLE
6.4 Manifests and Links

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#126]
The doc says: 

> This requirement should be extended to resources within a publication, such as a chapter, an image, or a mathematical formula. To achieve these, the manifest should contain the necessary information to make the mapping of URIs possible.

That's a really silly requirement - specially when HTML already makes those relationships explicit. 

Drop this.

**Comment by marcoscaceres** [comment]
Also: 

> and that reference must be unique, stable and retrievable on the Web. 

"stable and retrievable on the Web." is an oxymoron :)

**Comment by marcoscaceres** [comment]
> An archival service wants to harvest (spider) a PWP, and expects to find in the manifest what it needs make sure it gets all the pieces of the PWP that must be archived, even if on separate servers.

This is also silly... specially given that it's markup that contains the links.

**Comment by iherman** [comment]
> > An archival service wants to harvest (spider) a PWP, and expects to find in the manifest what it needs make sure it gets all the pieces of the PWP that must be archived, even if on separate servers.
> 
> This is also silly... specially given that it's markup that contains the links.

I do not agree with the characterization. Yes of course, an HTML file does contain a lot of links. The question is: which of those links should be followed for archival, and which should not? Obviously, an archival service may not want to take in the whole of the Web...

Getting back to the original issue/requirement: the question is whether a WP should consists only of resources that are 'local', for example referred to via relative URL-s only, or should the "manifest" (note the quote marks:-) allow for any URL-s, including to resources that are on a different domain altogether.

To take a very specific example. If one talks about EPUB, most of the resources are really meant to be in the package. Eg, when I convert a W3C TR document into EPUB, I have to create local copies of the CSS files that are in www.w3.org/Styles/..., and change the local references accordingly. If I have a Web Publication I should not be forced to make such thing, just list the www.w3.org/Styles/... as one of the resources that should be made available offline for a proper display of the TR document. Or should be contained in an archived version when needed. On the other hand, the documents in the references' section should not be listed in a similar way, they can just stay external references even if the document is offline.

**Comment by GarthConboy** [comment]
Excellent description in last paragraph of Ivan's previous.

**Comment by nullhandle** [comment]
A set of links in the markup is necessary but not sufficient for archiving. The crawler treats in links and resources, but the objects of interest for archiving are publications; the manifest provides the mapping between a set of links and a publication. Without the manifest, the crawler has to guess or be manually configured to perform this idiosyncratic mapping for every variant of every web-based publishing platform that is to be supported for archiving.

**Comment by marcoscaceres** [comment]
> A set of links in the markup is necessary but not sufficient for archiving. The crawler treats in links and resources, but the objects of interest for archiving are publications; the manifest provides the mapping between a set of links and a publication. Without the manifest, the crawler has to guess or be manually configured to perform this idiosyncratic mapping for every variant of every web-based publishing platform that is to be supported for archiving.

Yes, but that's a problem with HTML that we should then fix. It's silly to come up with a different format instead of fixing the source of the problem.

**Comment by iherman** [comment]
@marcoscaceres, I am not sure I agree this is an HTML problem. HTML is consistent with itself, and I am not sure what one would do with HTML. It is a problem with, in this case, the way archiving works which needs some additional information. I do not see why this type of information should not be part of an (extended) manifest.

Note that the content of the manifest may not be "these are the resources to be included in an archive" but, rather, "these are the resources that should _not_ be included in an archive" which, at least for a publication, may be a much shorter list. Ie, it may be a complementary information to the the result of a crawl.

Note that putting that kind of information into HTML (e.g., in the form of a specific value for a `@rel` attribute on an `a` element) would not work either; the same HTML source might be used by different publications, and the fact whether a resource should be part of an archive is publication dependent...

**Comment by lrosenthol** [comment]
Manifest section has undergone major surgery.  It still puts forth a number of use cases and reasons why a manifest is needed for (P)WP, but in ways that more align with the web platform and aren't completely focused on a packaged version.  @marcoscaceres let me know.

**Comment by marcoscaceres** [comment]
I'll try to find time to do another detailed review in the next week or two.

**Comment by iherman** [comment]
> On 10 Oct 2016, at 05:46, Marcos Cáceres notifications@github.com wrote:
> 
> I'll try to find time to do another detailed review in the next week or two. 

Thanks Marcos.

Note, however, that Leonard's (major!) work is only the first phase. We will have a call today reviewing all this and the next phase to reorganize the top level structure of the document possibly separating WP and and packaging better. That may take a while, though…

**Comment by marcoscaceres** [comment]
Ok, please ping when ready 🤓

**Comment by TzviyaSiegman** [comment]
resolved in major document edit and reorg. See specifically http://w3c.github.io/dpub-pwp-ucr/index.html#identify_const_resources and http://w3c.github.io/dpub-pwp-ucr/index.html#remap_links
