### ISSUE TITLE
6.5 Alternative Reading Orders

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#128]
The requirement is:

> Req. 29: The manifest may include alternative reading orders.

This presupposes that the reading order should be stipulated in a manifest - it doesn't have to be. Please decouple this from the manifest entirely.

The requirement should be:

> Req. 29: A publication can include alternative reading orders.

**Comment by marcoscaceres** [comment]
> It is up to the user agent how this alternative reading order is conveyed to the reader (via some suitable user interface techniques).

It's absolutely not! It's up to the author.

**Comment by iherman** [comment]
> On 28 Sep 2016, at 04:38, Marcos Cáceres notifications@github.com wrote:
> 
> The requirement is:
> 
> Req. 29: The manifest may include alternative reading orders.
> 
> This presupposes that the reading order should be stipulated in a manifest - it doesn't have to be. Please decouple this from the manifest entirely.
> 
> The requirement should be:
> 
> Req. 29: A publication can include alternative reading orders.

Terminology again, I am afraid...

**Comment by iherman** [comment]
> > It is up to the user agent how this alternative reading order is conveyed to the reader (via some suitable user interface techniques).
> 
> It's absolutely not! It's up to the author.

I am not sure I agree. The author/publisher provides alternative reading orders, and it is up to the user agent to act on it using a user interface it provides. Some of them will provide alternative menus to choose from, others may choose to provide sound output asking the user to choose among the different reading orders; I do not think this is up to the authors and/or the publisher to decide.

There _may_ be cases when the author wants to do that, e.g., for childrens' books. So the sentence might say:

> It may be up the user agent how this alternative reading order is conveyed to the reader (via some suitable user interface techniques).

There may be more complex cases but I am not sure it is to be get into in this document.

**Comment by lrosenthol** [comment]
This is where we end up back in the discussion that Dave Cramer raised
earlier - how much burden ends up on the author/publisher to provide the
experiences integrated into the publication (most likely via JS) VS a set
of declarative statements that are entirely up to the UA to process.

EPUB currently prefers the latter while the web prefers the former.  Other
formats such as Word/docx or PDF take a mixed approach, where the primary
experience is authored specified but there exist additional material (eg.
bookmarks) that are entirely in the province of the UA.  I suspect we'll
end up in the same hybrid mode at the end of the day - but not sure where
the line is drawn.

**Comment by GarthConboy** [comment]
I'm not 100% sure would view this "use case" as a requirement, perhaps a "nice to have."

In EPUB there is a <spine> with the primary reading order -- is this use case a nod to the @linear mess, or alternate orders in the Nav file?  Or, just proposed as a potential good idea to address those oft discussed "choose your own adventure" publications (which, for me, links [or yes JS] work just fine).

**Comment by lrosenthol** [comment]
I left in the section but cleaned it up and aligned it with the primary reading order section.  I also moved it closer in the document to the primary, so that they are more related to each other.  @GarthConboy and @iherman, let me know what you think.

**Comment by iherman** [comment]
@lrosenthol I am fine with what you did
