### ISSUE TITLE
Use case review: Publishing Workflow Effectiveness

### ISSUE THREAD

**Issue by rdeltour** [w3c/dpub-pwp-ucr#13]
> - 11. [Publishing Workflow Effectiveness](https://www.w3.org/dpub/IG/wiki/UseCase_Directory#Publishing_Workflow_Effectiveness)

Only 1 use case (["Tansclusion 01"](https://www.w3.org/dpub/IG/wiki/Transclusion_01))  about PWPs using shared components at runtime.

**Evaluation**: Is it in scope?

**Comment by iherman** [comment]
> On 29 Jan 2016, at 23:30, Romain Deltour notifications@github.com wrote:
> 1. Publishing Workflow Effectiveness https://www.w3.org/dpub/IG/wiki/UseCase_Directory#Publishing_Workflow_Effectiveness
>    Only 1 use case ("Tansclusion 01" https://www.w3.org/dpub/IG/wiki/Transclusion_01) about PWPs using shared components at runtime.
> 
> Evaluation: Is it in scope?

I have no idea! :-) Maybe Markus can tell us, he put it up there...

**Comment by lrosenthol** [comment]
Well, this pre-supposes that a PWP has multiple renditions.  I don't know that we've agreed to that yet

But supposing that it does, then I agree that shared components/resources across the renditions is important.  How that is accomplished is a detail of the format (and out of scope)

**Comment by dauwhe** [comment]
I hope we haven't agreed to multiple renditions yet. It adds incredible complexity, and I'm not convinced it's a good idea in general.
