### ISSUE TITLE
9.3 Building a Custom PWP

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#134]
Section "9.3 Building a Custom PWP" should be retitled "9.3 Building a Custom Reading Experience". Also, the use case for Buffy applies generally to everyone with a limited data plan (or limited time to read something).

**Comment by iherman** [comment]
I would agree with this: the issue is not build a new PWP but to build and alternative, or custom, reading approach in terms of a different ToC, for example.

Cc: @clapierre

**Comment by marcoscaceres** [comment]
Different ToCs is fine, but the requirement is really then about having the ability to generate alternative ToCs on the fly. 

Would be good to gather real examples of publications that do this, so we can look at them in detail.

**Comment by lrosenthol** [comment]
@clapierre may not be happy with it, but in my latest draft, I removed this entire section (well, commented it out).  The reason I did so is that a PWP can't do this - it's not a requirement of a PWP.  If anything, this is a use case that we want to ensure isn't prevented by the technical choices of PWP - but in and of itself, it's not specific to either PWP or the UA's for same.

**Comment by clapierre** [comment]
ACTION: Charles will move one of our use-cases that was commented out into Rec20 after Heather has finished updating the gh_pages branch from Leonard.

**Comment by iherman** [comment]
It is now part of #157, including Charles' changes
