### ISSUE TITLE
Joe and the teacher 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#136]
In section, 10.1 Limiting a PWP’s features

> Joe, a student, has completed his classroom assignment which was to use PWP annotations to complete the text’s quizzes, and uploads the document to the school’s classroom management web service. The teacher can safely read the PWP on the web because the service has automatically stripped the document of all untrusted scripts.

I'm confused, how was Joe able to insert untrusted scripts in the first place? Also, if the service has stripped out scripts, then how is this a requirement on a PWP?

**Comment by GarthConboy** [comment]
+1

**Comment by lrosenthol** [comment]
I updated the text in the latest draft with him putting those scripts in the annots he added.
