### ISSUE TITLE
10.4 Escalating trust

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#137]
I can't seem to parse Req. 50. I don't know what it's trying to say or elude to.

**Comment by lrosenthol** [comment]
It's another aspect of the idea (that you and @sideshowbarker) are not
enamored with, where we (or at least I) believe that we will need an
extended security model based on trust.

**Comment by lrosenthol** [comment]
I've cleaned up the description and the example to make this a LOT clearer.  See commit 5324dd8
Let us know what you think.

**Comment by marcoscaceres** [comment]
Though I disagree with the requirement, It's much more clear 👍
