### ISSUE TITLE
Reading and publishing anonymously

### ISSUE THREAD

**Issue by eshellman** [w3c/dpub-pwp-ucr#147]
Hi everyone!

There is an important use case that is touched on implicitly that I believe should be made explicit. 

One reason people have used non-centralized distribution in the physical world is to avoid censorship and to read and/or publish "dangerous" materials without fear. Thus the case for side-loading, emailing of documents, etc. But here side-loading is not the fundamental use-case, anonymous reading in the presence of network surveillance is the use case.

At the present time, Tor is the best technology available affording anonymous use of web sites. Tor hidden services are the best technology for anonymous publishing. A Tor browser can be used to download documents, and these can be read with a manageable risks that the reader's anonymity can be pierced.

The practical implication for PWP is that the security model being used for service workers may not be compatible with that of services that support strong anonymity.

Note that the aspect of "Privacy" discussed in this document is that of private communication, rather than anonymous communication. An additional example in section 3.1 should be sufficient to make this use case explicit.

Eric

**Comment by iherman** [comment]
Thanks for your comment, @eshellman!

> The practical implication for PWP is that the security model being used for service workers may not be compatible with that of services that support strong anonymity.

Can you elaborate on that? (I simply do not know.) AFAIK, the security requirement of Service Workers rely on the fact that one is required to serve everything with `HTTPS` instead of `HTTP`. Is that in contradiction with the usage of Tor?

FWIW, I think adding a use case along these line is a good idea. However, as a result of the recent wave of issues, and the subsequent discussion at TPAC, we have decided to go through a thorough reorganization of the document. Ie, we should wait for that to happen (1-2 weeks more) before we do the specifics.

**Comment by eshellman** [comment]
I can reach out to the Tor developers for comment. Tor hidden services use urls like http://1234567.onion/ and the entire connection is encrypted. The Tor Browser is currently based on Firefox and they have to mod the Javascript implementation extensively to improve privacy. But security models and their interaction with privacy can be very complicated and I have no idea if allowing service workers in Tor would even be contemplated.

Which leads me to suggest (crazily?): Maybe a PWP scripting sandbox model could look at Tor instead of the "Open Web" for ways to let javascript work without giving away the store.

**Comment by dgoulet** [comment]
Hi there, David from Tor. :)

If I understand correctly, the PWP tool only serves through HTTPS. So Tor onion services (.onion)[1] are e2e encrypted so there is not really a need for HTTPS although there is one for extra authentication of the domain that is the .onion address put in the altname of an EV cert for instance.

So ideally here, you would have your service be able to accept HTTP connection on at least localhost so Tor can connect to it when receiving a request on the .onion.

Second consideration is what eshellman brought up is on the client side of PWP, is there some information sent back to the service that could endanger privacy that is help identify the client machine or IP address or anything that could be used to find out the user identity. That will have to be at the application level.

Hope this help, don't hesitate to ask me more questions! (And hopefully I understood what was asked here :).

[1] https://www.torproject.org/docs/tor-hidden-service.html.en

**Comment by TzviyaSiegman** [comment]
Hi @dgoulet! thanks for taking a look. At this point, PWP is a list of use cases, not a specification or a tool, so we don't yet know many of the details such as whether it works if it works exclusively on HTTPS. If Service Workers is the method through which PWP is implemented, then it is likely contingent on HTTPS.  Please feel free to read the full document and comment or add to the use cases. Please note that the whole document is about to be re-organized though.

**Comment by eshellman** [comment]
@TzviyaSiegman @iherman Would you like me to take a shot at adding an anonymous reading use case or will you add something in the reorganized document?

**Comment by TzviyaSiegman** [comment]
@eshellman, please write a use case! Thanks

**Comment by iherman** [comment]
> @TzviyaSiegman https://github.com/TzviyaSiegman @iherman https://github.com/iherman Would you like me to take a shot at adding an anonymous reading use case or will you add something in the reorganized document?

I think we should wait until we have a new draft, ie, after the reorg. But I would personally prefer if you made a first shot at that point, to avoid misinterpreting your thoughts...

**Comment by eshellman** [comment]
that was the PR you merged.

**Comment by iherman** [comment]
Part of PR #157, too. Closing
