### ISSUE TITLE
Use case review: Pagination/DOM interaction

### ISSUE THREAD

**Issue by rdeltour** [w3c/dpub-pwp-ucr#15]
> - 14. [Pagination/DOM interaction](https://www.w3.org/dpub/IG/wiki/UseCase_Directory#Pagination.2FDOM_interaction)
- ["Page representation in the DOM"](https://www.w3.org/dpub/IG/wiki/RepresentationInDOM), about providing an API to the page model.
- ["Showing a specific page of content"](https://www.w3.org/dpub/IG/wiki/DisplayPage), about providing an API to display a specifc page
- ["Showing more than one page of content"](https://www.w3.org/dpub/IG/wiki/MultiPages), about rendering multiple pages simultaneously
- ["Determine what page a particular element appears on"](https://www.w3.org/dpub/IG/wiki/ElementToPage), also applies to text offsets.
- ["Specify how pages are referenced"](https://www.w3.org/dpub/IG/wiki/PageIdentifiers) is about how page progress is rendered, how pages impact bookmarks.
- ["Define events to notify when a page is ready/visible"](https://www.w3.org/dpub/IG/wiki/PageEvents)
- ["Functional Requirements for Pagination"](https://www.w3.org/dpub/IG/wiki/Functional_Requirements_for_Pagination)

**Evaluation**: are these in scope for the PWP use case doc? or better off in a dedicated document?

**Comment by iherman** [comment]
> On 29 Jan 2016, at 23:31, Romain Deltour notifications@github.com wrote:
> 1. Pagination/DOM interaction https://www.w3.org/dpub/IG/wiki/UseCase_Directory#Pagination.2FDOM_interaction
>    "Page representation in the DOM" https://www.w3.org/dpub/IG/wiki/RepresentationInDOM, about providing an API to the page model. Evaluation:
>    "Showing a specific page of content" https://www.w3.org/dpub/IG/wiki/DisplayPage, about providing an API to display a specifc page
>    "Showing more than one page of content" https://www.w3.org/dpub/IG/wiki/MultiPages, about rendering multiple pages simultaneously
>    "Determine what page a particular element appears on" https://www.w3.org/dpub/IG/wiki/ElementToPage, also applies to text offsets.
>    "Specify how pages are referenced" https://www.w3.org/dpub/IG/wiki/PageIdentifiers is about how page progress is rendered, how pages impact bookmarks.
>    "Define events to notify when a page is ready/visible" https://www.w3.org/dpub/IG/wiki/PageEvents
>    "Functional Requirements for Pagination" https://www.w3.org/dpub/IG/wiki/Functional_Requirements_for_Pagination
>    Evaluation: are these in scope for the PWP use case doc? or better off in a dedicated document?
> 
> —

I am not good in DOM/JavaScript, but they could be listed as programming specific requirements when talking about pagination.

**Comment by lrosenthol** [comment]
I would argue that APIs are out of scope for PWP.  I don't see us standardizing APIs.

Ensuring that APIs could be built - sure - but the specifics of the API, no.

**Comment by iherman** [comment]
> On 4 Feb 2016, at 08:49, lrosenthol notifications@github.com wrote:
> 
> I would argue that APIs are out of scope for PWP. I don't see us standardizing APIs.
> 
> Ensuring that APIs could be built - sure - but the specifics of the API, no.

Let us make the difference between what is in or out of scope in term of PWP as a general concept and whether it will or will not standardized. The DPUB IG does not standardize anything anyway; at some point, hopefully, a Working Group will do it and the in or out scope becomes a question when chartering that group.

More to the point: there are discussion whether a generic API would make sense or not. Look at the discussion leading to the POM Community Group[1].

[1] https://www.w3.org/community/pom/
