### ISSUE TITLE
2.1.2 - readability of requirement

### ISSUE THREAD

**Issue by mattgarrish** [w3c/dpub-pwp-ucr#155]
Minor nit:

> A Web Publication should conform to all the requirements of horizontal dependencies.

The placement of the word "all" in this requirement is confusing as it makes "horizontal dependencies" sound like a single entity of some kind instead of a plurality of concerns.

Better might be: "A Web Publication should conform to the requirements of all horizontal dependencies."

**Comment by iherman** [comment]
Thanks @mattgarrish. I updated the text accordingly.
