### ISSUE TITLE
"Write Protections"

### ISSUE THREAD

**Issue by riannella** [w3c/dpub-pwp-ucr#160]
The use case:
  https://www.w3.org/TR/2017/NOTE-pwp-ucr-20170502/#protections
is called "Write Protections"
But the example with Alice is clearly more than that:
"retains specific protections on what Bob is able to do with the publication and its content."

Perhaps this should be broadened to "permissions and obligations"?

Of which W3C has a solution ;-)

**Comment by francofaa** [comment]
Heading has since been renamed to "Protection". Related issue opened #213 on whether the content of the requirement is problematic.
