### ISSUE TITLE
offlining use cases 

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/dpub-pwp-ucr#161]
From Wolfgang via email (needs review)

Use Case 1:

Kathrin, a student at a German university has to write a scientific paper for a seminar. If she refers to or quotes from online resources, she is obliged to make all these resources available to her tutor on a CD-ROM or DVD which she should submit together with her paper. The rationale for this rule is that the tutor should have an easy and stable access to the resources Kathrin has used at any time later when he or she checks the paper. Part of this checking is to see whether citations are properly marked as such and correct, to be able to gauge the degree of independence from the sources, etc. As any resource on the Web could become unavailable (change of address, technical problems, etc.) or be altered at any time, this guarantees that the resources for her paper would persist.

Use Case 2:
Lea is writing her senior thesis to get the degree of a B.Sc. She accesses the Internet via WLAN, but due to the multitude of WLAN devices in the house she lives in, the WLAN connection is shaky and sometimes even breaks down abruptly. To ensure that her work won’t be interrupted now and again because she can’t access some resources and also to guarantee that the resources she used and quoted from be persistent, she downloads them to an external hard drive. A WP allows her to download the whole publication as a single logical unit in one step and not having to download each chapter separately.

**Comment by HadrienGardeur** [comment]
Use case 1 reads like a use case for packaging.

Use case 2 could be for offlining until that part:

> To ensure that her work won’t be interrupted now and again because she can’t access some resources and also to guarantee that the resources she used and quoted from be persistent, she downloads them to an external hard drive. A WP allows her to download the whole publication as a single logical unit in one step and not having to download each chapter separately.

IMO, we shouldn't talk about offlining at all. Instead, we should strictly talk about:

- packaging
- or caching

Packaging is meant to store a complete and stable version of a WP, while caching is meant to provide access to the resources of the publication if the connection is flaky, slow or you need to go offline for a limited period of time.

**Comment by francofaa** [comment]
Hi @TzviyaSiegman , [Packaging](https://w3c.github.io/dpub-pwp-ucr/#document-packaging) [use case](https://w3c.github.io/dpub-pwp-ucr/#uc_pwp_single_unit) covers much of item one. [Offline requirement](https://w3c.github.io/dpub-pwp-ucr/#offline) [use case](https://w3c.github.io/dpub-pwp-ucr/#uc_offline_synchronization) appears to cover the other use case suggested here. Is this safe to close?

**Comment by TzviyaSiegman** [comment]
@francofaa yes, ok to close
