### ISSUE TITLE
Use cases: Annotating across states

### ISSUE THREAD

**Issue by bjdmeest** [w3c/dpub-pwp-ucr#17]
state-wise, I currently assume the following:
- a PWP can be unpacked or packed
- a PWP can be online (http), offline (cache), or downloaded (file). Other variations like accessing via FTP etc. are not excluded.
1. Writer Annie has her book published on her own web space as a PWP [http/unpacked]. Reader Bob reads it online, and selects a nice quote to bookmark via its browser PWP bookmarking plugin: PWPMark-plugin.
2. Writer Annie has her book published on her own web space as a PWP [http/unpacked]. Reader Bob caches the PWP [cache/unpacked], reads it offline, and selects a nice quote to bookmark using PWPMark-plugin.
   - When Bob re-opens the offline PWP, the booksmarks are shown via PWPMark-plugin
   - When Bob re-visits the original PWP, PWPMark-plugin can also show Bob's bookmarks in the online version.
3. Writer Annie has her book published on her own web space as a PWP [http/packed]. Reader Bob opens it online using the PWP reading plugin PWPRead-plugin, and selects a nice quote to bookmark via PWPMark-plugin.
4. Writer Annie has her book published on her own web space as a PWP [http/packed]. Reader Bob caches it using a plugin [cache/packed], and selects a nice quote to bookmark via PWPMark-plugin.
5. Writer Annie has her book published on her own web space as a PWP, both packed [http/packed] as unpacked [http/unpacked]. Reader Bob reads [http/unpacked] online and selects a nice quote to bookmark via PWPMark-plugin. Then, Bob downloads [http/packed] to his local filesystem [file/packed] to open in his reading system of choice, namely, PWPRead-soft.
   - PWPRead-soft synchronizes with Bob's PWPMark profile, and can show Bob's bookmarks when he continues reading [file/packed]

**Comment by bjdmeest** [comment]
[lrosenth]: I have to disagree with your creating a new flavor – cached.  Caching is a feature of an RS and NOT part of a file format, such as PWP.

However, if you simply replace all instances of cached with local or downloaded, then so far so good for annotating across states.

**Comment by bjdmeest** [comment]
Does that mean only two protocol states are assumed: _online_ and _offline_? I made the distinction because I don't think we should limit us to only two (what about a PWP with online videos vs the same PWP with embedded videos?).
If you however mean that caching is an implementation detail, and we should just change the name to _local_ (i.e., could be different from _downloaded_) then I fully agree :)

**Comment by lrosenthol** [comment]
I guess there are really two dimensions:
- location of the PWP itself (local vs. remote)
- location of resources of the PWP (connected vs. disconnected).

So that would be a total of four possible cases (though at least one - remote+disconnected - doesn't make much sense)

**Comment by iherman** [comment]
> On 4 Feb 2016, at 08:47, lrosenthol notifications@github.com wrote:
> 
> I guess there are really two dimensions:
> 
> location of the PWP itself (local vs. remote)
> location of resources of the PWP (connected vs. disconnected).
> So that would be a total of four possible cases (though at least one - remote+disconnected - doesn't make much sense)

I have a feeling of déjà vu. We went through this discussion a while ago, when we looked into the terminology, and we came up with, indeed, four states, albeit slightly different ones, see

http://w3c.github.io/dpub-pwp/#state_definition http://w3c.github.io/dpub-pwp/#state_definition

**Comment by hlflanagan** [comment]
Is this one use case, or five? The requirements seem to circle around a plugin as opposed to features of the PWP itself.

**Comment by bjdmeest** [comment]
They are five use cases, all circling around the fact that locating a resource within a PWP should not depend on the PWP's state, using some annotation scenarios. That state independent locator should be part of the PWP. But details of the plug-in might surely be omitted, I am not sure about that :)

**Comment by hlflanagan** [comment]
Items merged into UCR doc
