### ISSUE TITLE
Private/Public locators

### ISSUE THREAD

**Issue by bjdmeest** [w3c/dpub-pwp-ucr#18]
1 Bob is reading in PWPRead-soft, and makes private annotations. These annotations can be - via Bob's PWPMark profile - synced across devices.
2 Bob makes a couple of his annotations public. Chris also has a PWPMark profile, and choses to show all public annotations whilst reading using PWPRead-plugin. Chris sees Bob's annotations whilst reading the same document.
- this could be extended to more 'fine-grained' user access, e.g., two lawyers annotating the same contract as a PWP on their own computer. These annotations are shared only in specific groups, depending on what the PWPMark software allows.

**Comment by bjdmeest** [comment]
[lrosenth]: The concept of public and private annotations is out of scope and has nothing to do with PWP

**Comment by bjdmeest** [comment]
I actually agree :). Locators should have no notion on the context they are used in. So I guess this can be closed, if there are no counter-arguments :)

**Comment by rdeltour** [comment]
> So I guess this can be closed, if there are no counter-arguments :)

I think the interesting part of this UC is about sharing annotations (i.e. locators) between two users, about PWPs which may not be in the same state. But this is covered in #17, so I'm closing this one.
Feel free to reopen if you disagree.

**Comment by iherman** [comment]
> On 4 Feb 2016, at 08:45, Ben De Meester notifications@github.com wrote:
> 
> [lrosenth]: The concept of public and private annotations is out of scope and has nothing to do with PWP

I do not agree. We know that annotations is a very important feature for publications and there are numerous use cases, even a separate Working Group, on this. Placing or associating an annotation with a PWP is therefore a requirement, and a PWP must ensure that this can be done. This may (and does, it came up in the discussions several times) has consequences on the concept of locators and how they work. Ie, these _are_ important use cases in my view.

**Comment by rdeltour** [comment]
> Placing or associating an annotation with a PWP is therefore a requirement, and a PWP must ensure that this can be done.

I think we all agree on that.

> This may (and does, it came up in the discussions several times) has consequences on the concept of locators and how they work. Ie, these _are_ important use cases in my view.

Yes, but I think this is covered by #17 already. This UC (#18) doesn't cover anything new; the only difference was that it introduces private/public annotations as a concept, but this is totally independent IMO (it's annotation metadata) and has absolutely no impact on the URLs. Would you agree?

If not, feel free to reopen!

**Comment by iherman** [comment]
I am sorry. You are right about #17. I reacted on the overall statement of https://github.com/w3c/dpub-pwp-ucr/issues/18#issuecomment-179694505 from @lrosenthol (as forwarded by @bjdmeest)

**Comment by rdeltour** [comment]
> I am sorry. You are right about #17 https://github.com/w3c/dpub-pwp-ucr/issues/17. 

OK, no prob. Let's keep this issue closed then :smile:
