### ISSUE TITLE
Should we define "handle"?

### ISSUE THREAD

**Issue by dauwhe** [w3c/dpub-pwp-ucr#188]
This doc uses the term "handle," which I'm only familiar with because of songs about truckers and citizen's band radios that were popular in the United States in the 1970s. 

What does "handle" mean in the context of web addresses? Is a DOI a "handle" even though it's also a legitimate URL? Do we just mean URLs that may redirect? Isn't that always possible on the web?

**Comment by atyposh** [comment]
Yes, the DOI is an implementation of the CNRI's "handle system". I should add an explanation and link. Thanks for this!

> The Handle System is the Corporation for National Research Initiatives's proprietary registry assigning persistent identifiers, or handles, to information resources, and for resolving "those handles into the information necessary to locate, access, and otherwise make use of the resources"
