### ISSUE TITLE
Spec tool: Bikeshed or Respec?

### ISSUE THREAD

**Issue by rdeltour** [w3c/dpub-pwp-ucr#2]
We have to decide on the spec editing tool to use, [Respec](https://github.com/darobin/respec) or [Bikeshed](https://github.com/tabatkins/bikeshed).

@dauwhe seems to have a pref for Bikeshed; should we just go ahead and set it up?

**Comment by lrosenthol** [comment]
bikeshed seems to be the tool of choice for the W3C, so would be good to
utilize that...

**Comment by iherman** [comment]
> On 20 Jan 2016, at 18:28, lrosenthol notifications@github.com wrote:
> 
> bikeshed seems to be the tool of choice for the W3C, so would be good to
> utilize that…

Without taking sides, this statement is not correct. I do not have exact statistics, but I have the impression that more WG-s use respec these days than bikeshed.

Ivan

> On Wed, Jan 20, 2016 at 12:22 PM, Romain Deltour notifications@github.com
> wrote:
> 
> > We have to decide on the spec editing tool to use, Respec
> > https://github.com/darobin/respec or Bikeshed
> > https://github.com/tabatkins/bikeshed.
> > 
> > @dauwhe https://github.com/dauwhe seems to have a pref for Bikeshed;
> > should we just go ahead and set it up?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/w3c/dpub-pwp-ucr/issues/2.
> > 
> > —
> > Reply to this email directly or view it on GitHub https://github.com/w3c/dpub-pwp-ucr/issues/2#issuecomment-173291797.

---

Ivan Herman, W3C
Digital Publishing Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by dauwhe** [comment]
CSSWG uses only Bikeshed, and I very much like Bikeshed. But setting it up is non-trivial (if you want to use it locally) and does have lots of CSS-specific features. If I was editing a doc by myself, I would absolutely use Bikeshed, but am probably more comfortable recommending Respec for a group of people who have no experience with either tool.

**Comment by dauwhe** [comment]
I've created a minimal index.html page using Respec. Let the authoring begin!
