### ISSUE TITLE
Expected Behavior of Reading Order in Web Publications

### ISSUE THREAD

**Issue by GeorgeKerscher** [w3c/dpub-pwp-ucr#204]
Presentation of the reading order in a Web Publication  is an affordance the Reading System (user agent) should provide. The manifest provides the list of files in sequential order. In addition, there is the Table of Contents, which provides the ability to navigate to pre defined locations in the publication. The reading system should enable the end user to read through the publication in sequential order.
 
Note: Many publications are not expected to be read in order, e.g. cookbooks, dictionaries, reference works, journals. However, the principle of supporting the reading order does not impact the effective use of reference materials.
 
Some considerations:

* The Reading System should enable the end user to start reading  at the first file in the publication and easily continue to read through the entire publication. 
* The Reading System should “remember” the last position read when the publication is closed.
* When reopening a publication, The Reading System should reopen the publication to the last known position.
* The Reading System should not require the end user to do something different when moving to the next file in the sequence.
 
Reading System functionality for synchronizing Reading order with the Table of Contents:
 
* The reading system should provide a mechanism to move to the table of contents without effecting the current reading position
* The Reading System should place focus on the heading of the current reading position in the TOC.
* If two or more headings are visible in the current viewport, place focus in the TOC on the first heading in the viewport. 
* When the end user selects a new location in the TOC, navigate to that file and heading in the content.
* The End user should be able to read continuously   from the new location.
 
Further considerations:

* The end user does not know how many files make up the publication. Having the end user move to the next file in the sequence is a burden  that should be avoided, e.g. go to the TOC and move down to the next heading you have not read and go to that location.
* The end user should not be required to hit a link at the end of a file to move to the next file.
* If the end user navigates by a page number in the publication, the Reading System should Track where the person is located so that moving to the TOC is correct. The correct location would be the first heading in the current viewport of that page number, i.e. page 10 is followed by a h2, the h2 is the current focused location in the TOC.
* Some Reading Systems may provide a breadcrumb (history) function that allows the end user to  navigate through a series of last known locations.
* Some Reading Systems may provide a go back function, which amounts to the last known location in the breadcrumb list.
* When searching a publication, the Reading System will take the user to a new location. This new location should enable continuous reading from this new location. Here too, the go-back function will be very useful. 

Issues not Addressed

* When there are entries in the TOC that are resources not in the reading order, we do not know what the behavior should be. For example, if the end user moves to a glossary, what would the reading order become?
* In titles that are choose your own ending, there are alternative paths through the publication. What is the reading order in these publications?
reading

**Comment by atyposh** [comment]
These suggestions were added to a branch (https://github.com/w3c/dpub-pwp-ucr/tree/user-agents-initial) that was not merged because we ultimately decided against adding UA specification to the UCR document.
