### ISSUE TITLE
Protection requirement problematic

### ISSUE THREAD

**Issue by francofaa** [w3c/dpub-pwp-ucr#213]
**From TAG review**: [requirement 17 (Protection)](https://w3c.github.io/dpub-pwp-ucr/#r_protection) seems like it may be problematic. (Similar for, say [UC 114](https://w3c.github.io/dpub-pwp-ucr/#uc_pwp-process_access_control).)

> Requirement: A Web Publication should be able to express the access control and write protections of the publication.

**Comment by atyposh** [comment]
I think I agree with the TAG reviewer that this may be problematic. The requirement (as currently stated) seems to suggest that the the WP is actively engaged in AC/DRM rather than simply being the subject of AC/DRM.

Perhaps we should restate this requirement as:

A Web Publication must not prevent any other system from expressing access control and write protections of the publication.

**Comment by francofaa** [comment]
Hi @duga , 

I wanted to address your concerns from yesterday. From yesterday's minutes: 

> Brady Duga: It seems like we’re forcing all these to have access control applied to them… there may be places where you want the opposite

I believe that there is not really a way for a Web Publication to prevent an access control system from applying access control. Additionally, using licensing and access control may be the main way to prevent any other system from enforcing a stricter version of access control. 

For example, an author intends a book to be freely available to everyone. They may want to apply an access control that explicitly states that no one should be prevented from accessing this book. In this way, another person could not take the book and apply their own more limiting access control to it. It seems that having this as an inherent quality of the WP itself is out of scope.

Here is a proposed rephrasing of the requirement which removes the MUST and prevention language:

> A Web Publication should allow for the application of access control and write protections of the publication.

Thanks,
Franco

**Comment by TzviyaSiegman** [comment]
tagging @duga (who is not ben dugas)

**Comment by francofaa** [comment]
Resolved by #225
