### ISSUE TITLE
Combine unique ID and Single Logical Resource requirements 

### ISSUE THREAD

**Issue by francofaa** [w3c/dpub-pwp-ucr#218]
Should we combine the requirements [6 Single Logical Resource  ](https://w3c.github.io/dpub-pwp-ucr/#r_single) and [4 Unique ID](https://w3c.github.io/dpub-pwp-ucr/#r_uid)?. Are these redundant? 

(@iherman , @tcole3 )

**Comment by iherman** [comment]
They are close but they may not be completely identical.

- (6) says that there is a URL for the whole collection as an individual "thing"
- (4) says that there must be URL for that thing.

Ie, they are not redundant, but I think they can be merged, something like:

"A Web Publication, as a collection of resources, must be identified by either a single URL or a unique handle that can be mapped to a single URL."
