### ISSUE TITLE
Using PWPs in web contexts/building a PWP reader as a progressive web app

### ISSUE THREAD

**Issue by baldurbjarnason** [w3c/dpub-pwp-ucr#22]
Based on our conversations at Rebus, one requirement that we have which might become an issue for PWP is that, to maximise distribution and reach, we'd like our baseline reader to be browser-based.

As in, our current plans (subject to change, of course) it'd be a progressive web app. Not an app built using browser tech (that might come later if the resources allow). 

This generally shouldn't be an issue except when it comes to javascript.

A web app can't allow third party javascript, not without limitations.

(All of these issues also apply to the preview of PWPs in websites that want to add their own chrome/UI to the preview.)

The options as I see them:
1. Sandboxed iframe. Has UX/UI downsides now that 'seamless' has been removed and is resource intensive (it's a whole new browsing context in a box). It's also a bit tricky to implement if you don't want to accidentally leave open security holes. It doesn't protect anything in older browsers or Opera Mini (which actually does support some JS) which means it _has_ to be supplemented by another approach anyway, thereby increasing the cost to implement.
2. Don't allow any javascript. The easiest method to implement.
3. Sandbox the javascript using Caja. Ties you either to Google's servers or to setting up your own implementation. Very resource- and engineering-intensive.
4. Whitelist JS files that are known to be safe using URLs and [integrity hashes](https://w3c.github.io/webappsec-subresource-integrity/).

(All of these limitations are _in addition_ to the limitations that need to be put in place to prevent PWPs from being a vector for malware in general. But that's a separate issue.)

The third option, the whitelist, would strike for us the right balance between effort and reward. This would, for example, let us support Google AMP files as if they were portable publications and let the community curate/build a set of open source custom elements that can be used on both regular websites and in portable publications. Given that custom elements are almost certainly going to be big, vetting the most popular ones for security and whitelisting would net you a lot of functionality.

**Comment by hlflanagan** [comment]
This doesn't really break down as a use case or a specific requirement, and may be out of the scope of the pwp-ucr. Something to discuss at TPAC?

**Comment by iherman** [comment]
Agreeing with @hlflanagan that this is not an issue for the UCR, but maybe it is for the (new version of the) PWP draft itself. @baldurbjarnason, I wonder how it would fit the latest version of the PWP draft (currently still in a [separate branch](https://rawgit.com/w3c/dpub-pwp/sync-with-ucr/index.html)). 

@baldurbjarnason, would it be possible to you to move this issue to the PWP issue list and close the issue in this repo? Just to make it administratively more manageable...

**Comment by baldurbjarnason** [comment]
From a use cases perspective this is covered by the current [draft use cases document](http://w3c.github.io/dpub-pwp-ucr/index.html#security) (specifically 10.1). I'm not sure I need more from the PWP than for it to accurately reflect the use cases document.
