### ISSUE TITLE
Use case review: Styling and layout

### ISSUE THREAD

**Issue by rdeltour** [w3c/dpub-pwp-ucr#3]
> - 1. [Styling and Layout](https://www.w3.org/dpub/IG/wiki/UseCase_Directory#Styling_and_Layout)
>   - 1.1. Lists
>   - 1.2. Pagination
>   - 1.3. Adaptive Layout
>     - 1.3.1. Device Adaption
>     - 1.3.2. User Adaption
>   - 1.4. Positionning

Markus [said](https://www.w3.org/2016/01/11-dpub-minutes.html#item01) these should be de-prioritized. Should some related cases be added eventually or is it left out entirely to the Layout and Styling TF?
## Lists

One UC (["Lists"](https://www.w3.org/dpub/IG/wiki/Lists)) related to hierarchical semantics and counter styling.

> This level of semantics is often perceived by publishers as insufficient to distinguish hierarchical outline lists with more complex numbering schemes 

I'm not sure I grasp the essence, in particular what's needed that HTML + CSS doesn't provide.

**Evaluation**: this is a very specific content-related UC, I don't think it needs to be integrated to PWP use cases.
## Pagination

One UC (["Tables 1"](https://www.w3.org/dpub/IG/wiki/Tables_1#Tables_1)) related to rendering of tables in paginated rendering.

**Evaluation**: pagination is obviously an important UC. We may want a UC that describes pagination-related issues when displaying content, but it should not be limited to tables. The issue is vast however. If we want a UC in this document, it must be high-level on what makes the problem particular to PWP? Details of pagination reqs for the larger generic web are better off in a specific document IMO.
## Adaptive layout

Only one UC (["Tables 1"](https://www.w3.org/dpub/IG/wiki/Tables_1#Tables_1)), the same as the pagination one described above.

**Evaluation**: to which extent adaptive layout issues are specific to PWP? (I'm not sure they are). Do we need a UC here?
## Positioning

One UC (["NakaTobira"](https://www.w3.org/dpub/IG/wiki/NakaTobira_01)) related to the Naka Tobira Japanese layout design.

**Evaluation**: not sure if specific to PWP or better off in a pagination-specific document. See Pagination above.

**Comment by iherman** [comment]
> On 29 Jan 2016, at 23:15, Romain Deltour notifications@github.com wrote:
> 1. Styling and Layout https://www.w3.org/dpub/IG/wiki/UseCase_Directory#Styling_and_Layout
>    1.1. Lists
>    1.2. Pagination
>    1.3. Adaptive Layout
>    1.3.1. Device Adaption
>    1.3.2. User Adaption
>    1.4. Positionning
>    Markus said https://www.w3.org/2016/01/11-dpub-minutes.html#item01 these should be de-prioritized. Should some related cases be added eventually or is it left out entirely to the Layout and Styling TF?
> 
> Lists
> 
> One UC ("Lists" https://www.w3.org/dpub/IG/wiki/Lists) related to hierarchical semantics and counter styling.
> 
> This level of semantics is often perceived by publishers as insufficient to distinguish hierarchical outline lists with more complex numbering schemes
> 
> I'm not sure I grasp the essence, in particular what's needed that HTML + CSS doesn't provide.
> 
> Evaluation: this is a very specific content-related UC, I don't think it needs to be integrated to PWP use cases.

I agree.

> Pagination
> 
> One UC ("Tables 1" https://www.w3.org/dpub/IG/wiki/Tables_1#Tables_1) related to rendering of tables in paginated rendering.
> 
> Evaluation: pagination is obviously an important UC. We may want a UC that describes pagination-related issues when displaying content, but it should not be limited to tables. The issue is vast however. If we want a UC in this document, it must be high-level on what makes the problem particular to PWP? Details of pagination reqs for the larger generic web are better off in a specific document IMO.

I think we should keep pagination as a UC. It is extremely important to be able to to do it on the Web at large, otherwise longer publications will never care about PWP.

I am looking, for a long time, for some sort of a study showing that pagination can be of a huge cognitive help on any Web page that is longer than a certain limit. This is a requirement that PWP has but that may be very useful for the Web.

> Adaptive layout
> 
> Only one UC ("Tables 1" https://www.w3.org/dpub/IG/wiki/Tables_1#Tables_1), the same as the pagination one described above.
> 
> Evaluation: to which extent adaptive layout issues are specific to PWP? (I'm not sure they are). Do we need a UC here?
> 
> Positioning
> 
> One UC ("NakaTobira" https://www.w3.org/dpub/IG/wiki/NakaTobira_01) related to the Naka Tobira Japanese layout design.
> 
> Evaluation: not sure if specific to PWP or better off in a pagination-specific document. See Pagination above.

See my comment above:-)

**Comment by rdeltour** [comment]
> I think we should keep pagination as a UC. It is extremely important to be able to to do it on the Web at large, otherwise longer publications will never care about PWP.

I agree: but precisely, wouldn't even deserve its own UC&R document?

> I am looking, for a long time, for some sort of a study showing that pagination can be of a huge cognitive help on any Web page that is longer than a certain limit. 

Maybe the papers referenced in [this comment on the blog post "a defense of pagination"](http://futureofthebook.org/blog/2010/12/09/a_defense_of_pagination/#comment-3625)?

**Comment by iherman** [comment]
> On 30 Jan 2016, at 11:34, Romain Deltour notifications@github.com wrote:
> 
> I think we should keep pagination as a UC. It is extremely important to be able to to do it on the Web at large, otherwise longer publications will never care about PWP.
> 
> I agree: but precisely, wouldn't even deserve its own UC&R document?
> 
> Ah! I did not think of this.

I would propose to keep it in one for now. If the pagination part becomes too voluminous or simply too complex on its own right, we can still decide to spawn it off later

> I am looking, for a long time, for some sort of a study showing that pagination can be of a huge cognitive help on any Web page that is longer than a certain limit.
> 
> Maybe the papers referenced in this comment on the blog post "a defense of pagination" http://futureofthebook.org/blog/2010/12/09/a_defense_of_pagination/#comment-3625?

I did not know this blog! I will look into it...

**Comment by tsiegman-wiley** [comment]
I believe the use case is constructing traditional outlines, some of which are described here [1]. These can be difficult to manage with basic HTML/CSS, especially when one needs to insert images or other objects in the middle. I don’t think this is a UC for PWP, but a more general issue.

[1] https://en.wikipedia.org/wiki/Outline_(list)

Tzviya Siegman
Digital Book Standards & Capabilities Lead
Wiley
201-748-6884
tsiegman@wiley.commailto:tsiegman@wiley.com

**Comment by hlflanagan** [comment]
Pagination is mentioned and linked in the first public working draft.
