### ISSUE TITLE
CSS Requirements section in Use Cases Document

### ISSUE THREAD

**Issue by dauwhe** [w3c/dpub-pwp-ucr#34]
Does [this ](http://w3c.github.io/dpub-pwp-ucr/#css-requirements-for-packaged-multiple-documents) make sense as a top-level section? Most other sections do not mention specific technical means (of course we know CSS will be involved). More importantly, I think most of the subsections belong with other headings. CSS customization is an aspect of personalization. Pagination is one of the fundamental requirements, as is navigation across document boundaries. 

Should we just move the use cases here, and delete the section?

**Comment by hlflanagan** [comment]
CSS has been integrated into other sections, as it made sense. No longer a top level section.
