### ISSUE TITLE
Use case review: Domain-specific Content Type

### ISSUE THREAD

**Issue by rdeltour** [w3c/dpub-pwp-ucr#4]
> - 2. [Domain-Specific Content Types](https://www.w3.org/dpub/IG/wiki/UseCase_Directory#Domain-Specific_Content_Types)
>   - 2.1. STEM
>   - 2.2. Assessments
>   - 2.3. Infographics
>   - 2.4. Comics/Manga

Only the first bullet contains use cases (["MathML"](), ["Chemistry UC"](), ["Diagrams and Graphing"](), ["Tables_1"](), ["Lists"]()).  
These basically say "a publisher wants to provide math/chemistry/diagram content. It must be accessible, scripatable, etc."

**Evaluation**: doesn't sound specific to PWP, I don't think content-specific UC are in scope for this document. If some aspects of content representation are not covered by the Web Platform, better off in a separate IG doc?

**Comment by iherman** [comment]
> On 29 Jan 2016, at 23:15, Romain Deltour notifications@github.com wrote:
> 1. Domain-Specific Content Types https://www.w3.org/dpub/IG/wiki/UseCase_Directory#Domain-Specific_Content_Types
>    2.1. STEM
>    2.2. Assessments
>    2.3. Infographics
>    2.4. Comics/Manga
>    Only the first bullet contains use cases ("MathML" applewebdata://572C51CA-7299-4FBE-9919-39FE977C9856, "Chemistry UC" applewebdata://572C51CA-7299-4FBE-9919-39FE977C9856, "Diagrams and Graphing" applewebdata://572C51CA-7299-4FBE-9919-39FE977C9856, "Tables_1" applewebdata://572C51CA-7299-4FBE-9919-39FE977C9856, "Lists" applewebdata://572C51CA-7299-4FBE-9919-39FE977C9856).
> 
> These basically say "a publisher wants to provide math/chemistry/diagram content. It must be accessible, scripatable, etc."
> 
> Evaluation: doesn't sound specific to PWP, I don't think content-specific UC are in scope for this document. If some aspects of content representation are not covered by the Web Platform, better off in a separate IG doc?

I tend to agree with this (not dismissing the importance of STEM, of course!)

**Comment by hlflanagan** [comment]
Domain specific things were mentioned where they made sense, though not with dedicated use cases.
