### ISSUE TITLE
Set max toc level to 2

### ISSUE THREAD

**Issue by halindrome** [w3c/dpub-pwp-ucr#42]
Having the detailed scenario (use case) titles in the ToC makes it hard to read.

**Comment by TzviyaSiegman** [comment]
Agreed. I think TOC is generated from headings. Is there a method to override that or put partial headings in the generated TOC?

**Comment by halindrome** [comment]
There is no way to limit the amount of text from the section name that is put into the ToC.  You can globally set the ToC level with the respec configuration setting "maxTocLevel" as defined at https://github.com/w3c/respec/wiki/maxTocLevel

You can mark individual sections such that they do not go into the ToC with the class "notoc".  I note that this special class is not documented in the wiki.  I will add something about that now.

**Comment by iherman** [comment]
> On 15 Aug 2016, at 16:35, Shane McCarron notifications@github.com wrote:
> 
> There is no way to limit the amount of text from the section name that is put into the ToC. You can globally set the ToC level with the respec configuration setting "maxTocLevel" as defined at https://github.com/w3c/respec/wiki/maxTocLevel https://github.com/w3c/respec/wiki/maxTocLevel
> You can mark individual sections such that they do not go into the ToC with the class "notoc". I note that this special class is not documented in the wiki. I will add something about that now.

Yep I saw that, but I do not think we want that; we do want those to appear in the TOC, just not the way they are there. I guess re-edit the file to look like

```
<section>
    <h2>This is the short title…</h2>
    <p class="requirement">The full text of the requirement</p>
```

Is the only way to do it cleanly, and use some CSS to bold and enlarge and underline and blink and… the requirement paragraph.

**Comment by hlflanagan** [comment]
Fixed in the first public working draft.
