### ISSUE TITLE
Use case review: Metadata

### ISSUE THREAD

**Issue by rdeltour** [w3c/dpub-pwp-ucr#6]
> - 4. [Metadata](https://www.w3.org/dpub/IG/wiki/UseCase_Directory#Metadata)
>   - 4.1. Publication-level
>   - 4.2. Resource/fragment-level

One UC (["Discovery of Accessible eBooks"](https://www.w3.org/dpub/IG/wiki/Metadata_pub_level#accessibility_1)) about a publisher providing metadata, the retailer exposing it, consumer searching it, etc.

**Evaluation**: this should be consolidated, notably to better describe the impact/interaction with the different states of the PWP (offline, packaged, unpackaged).

One UC (["Provenance of Digital Publications"](https://www.w3.org/dpub/IG/wiki/Provenance_of_Digital_Publications)), describing provenance as e.g. a scholarly paper derived from a dataset.

**Evaluation**: if I understand correclty, the concept of "provenance" here is not specific to PWP. However, we proably want a UC about identifying the "provenance" (canonical location) of a ported/offline PWP.

One UC (["Book semantic / StructSem UC"](https://www.w3.org/dpub/IG/wiki/StructSem_UC)) about structural semantics of headings (IIUC).

**Evaluation**: not specific to PWP; if not covered by HTML + ARIA-DPUB, then integrate to some other doc?

**Comment by iherman** [comment]
> On 29 Jan 2016, at 23:17, Romain Deltour notifications@github.com wrote:
> 1. Metadata https://www.w3.org/dpub/IG/wiki/UseCase_Directory#Metadata
>    4.1. Publication-level
>    4.2. Resource/fragment-level
>    One UC ("Discovery of Accessible eBooks" https://www.w3.org/dpub/IG/wiki/Metadata_pub_level#accessibility_1) about a publisher providing metadata, the retailer exposing it, consumer searching it, etc.
> 
> Evaluation: this should be consolidated, notably to better describe the impact/interaction with the different states of the PWP (offline, packaged, unpackaged).

+1

> One UC ("Provenance of Digital Publications" https://www.w3.org/dpub/IG/wiki/Provenance_of_Digital_Publications), describing provenance as e.g. a scholarly paper derived from a dataset.
> 
> Evaluation: if I understand correclty, the concept of "provenance" here is not specific to PWP. However, we proably want a UC about identifying the "provenance" (canonical location) of a ported/offline PWP.
> 
> +1
> One UC ("Book semantic / StructSem UC" https://www.w3.org/dpub/IG/wiki/StructSem_UC) about structural semantics of headings (IIUC).
> 
> Evaluation: not specific to PWP; if not covered by HTML + ARIA-DPUB, then integrate to some other doc?

Yes, this is in the realm of the DPUB ARIA work
