### ISSUE TITLE
link to EPUB leads to 404

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/dpub-pwp-ucr#69]
We need to create EPUB or remove link

**Comment by iherman** [comment]
That is github artifact. The epub is created, but did not put it into the folder where the editor's copy resides. The "real" publication on the W3C site (or its github snapshot: http://w3c.github.io/dpub-pwp-ucr/publishing-snapshots/FPWD/Overview.html) has the epub version and the link is fine...
