### ISSUE TITLE
Use case review: Content & Markup

### ISSUE THREAD

**Issue by rdeltour** [w3c/dpub-pwp-ucr#7]
> - 5. [Content & Markup](https://www.w3.org/dpub/IG/wiki/UseCase_Directory#Content_.26_Markup)
>   - 5.1. Structural Semantics
>   - 5.2. Other
## Structural semantics

4 UCs (["Index1/Behavioral UC1"](https://www.w3.org/dpub/IG/wiki/Behavioral_UC#Behavioral_1), ["Index2/Behavioral UC2"](https://www.w3.org/dpub/IG/wiki/Behavioral_UC2#Behavioral_2), ["Index3/Behavioral UC3"](https://www.w3.org/dpub/IG/wiki/Behavioral_UC3#Behavioral_3), ["Notes1/Behavioral UC4"](https://www.w3.org/dpub/IG/wiki/Behavioral_UC4#Behavioral_4))

**Evaluation**:
- structural semantics are covered by DPUB-ARIA, not specific to PWP.
- intra-publication linking requires a UC, although identification of range is probably out of scope for PWP.
- about the behavior (e.g. rendering a footnote in a popup): it can be 1. browser native, 2. provided by a RS (layer "on top" of the browser), 3. provided by JS "polyfills" in the pub. I think we need a behavioral UC here.

Another UC (["User added dictionary"](https://www.w3.org/dpub/IG/wiki/User_added_dictionary)) about using a PWP as a dictionary.

 **Evaluation**: probably out of scope for the first iteration of PWP?
## Other
- ["MediaSpecificMarkup"](https://www.w3.org/dpub/IG/wiki/Behavioral_UC5#Behavioral_5) is about identifying markup relevant to a specific media (e.g. print pages).
  **Evaluation**: out of scope
- ["ScrollDirection"](https://www.w3.org/dpub/IG/wiki/Behavioral_UC6#Behavioral_6) is about declaring a preferred scrolling direction.  
  **Evaluation**: out of scope for PWP? not sure.
- ["ContinuousSound"](https://www.w3.org/dpub/IG/wiki/Behavioral_UC7#Behavioral_7) is about having a background soundtrack.  
  **Evaluation**: out of scope, it's a generic web thing.
- ["Tables_1"](https://www.w3.org/dpub/IG/wiki/Tables_1#Tables_1) is already discussed in other issues #3 and #4.
- ["User directed styling modifications (font family)"](https://www.w3.org/dpub/IG/wiki/UserFontFamilyAdjustments) is about customizing the font used by RS/UA.  
  **Evaluation**: consolidate to describe the mecanics of browser/RS/publisher CSS?

**Comment by iherman** [comment]
> On 29 Jan 2016, at 23:19, Romain Deltour notifications@github.com wrote:
> 1. Content & Markup https://www.w3.org/dpub/IG/wiki/UseCase_Directory#Content_.26_Markup
>    5.1. Structural Semantics
>    5.2. Other
>    Structural semantics
> 
> 4 UCs ("Index1/Behavioral UC1" https://www.w3.org/dpub/IG/wiki/Behavioral_UC#Behavioral_1, "Index2/Behavioral UC2" https://www.w3.org/dpub/IG/wiki/Behavioral_UC2#Behavioral_2, "Index3/Behavioral UC3" https://www.w3.org/dpub/IG/wiki/Behavioral_UC3#Behavioral_3, "Notes1/Behavioral UC4" https://www.w3.org/dpub/IG/wiki/Behavioral_UC4#Behavioral_4)
> 
> Evaluation:
> 
> structural semantics are covered by DPUB-ARIA, not specific to PWP.
> +1
> 
> intra-publication linking requires a UC, although identification of range is probably out of scope for PWP.
> I think it is a UC for PWP; some of its definitions may be out of scope for this IG or for a future WG. 

In general, I think that being 'out of scope' should be a possible answer to a UC, but that does not invalidates the UC itself. Just that some other groups/organizations have to deal with it.

> about the behavior (e.g. rendering a footnote in a popup): it can be 1. browser native, 2. provided by a RS (layer "on top" of the browser), 3. provided by JS "polyfills" in the pub. I think we need a behavioral UC here.
> +1
> Another UC ("User added dictionary" https://www.w3.org/dpub/IG/wiki/User_added_dictionary) about using a PWP as a dictionary.
> 
> Evaluation: probably out of scope for the first iteration of PWP?
> 
> See above. It is a valid UC, but we may decide not to work on it for now.
> Other
> 
> "MediaSpecificMarkup" https://www.w3.org/dpub/IG/wiki/Behavioral_UC5#Behavioral_5 is about identifying markup relevant to a specific media (e.g. print pages). Evaluation: out of scope
> +1
> "ScrollDirection" https://www.w3.org/dpub/IG/wiki/Behavioral_UC6#Behavioral_6 is about declaring a preferred scrolling direction.
> Evaluation: out of scope for PWP? not sure.
> "ContinuousSound" https://www.w3.org/dpub/IG/wiki/Behavioral_UC7#Behavioral_7 is about having a background soundtrack.
> Evaluation: out of scope, it's a generic web thing.
> "Tables_1" https://www.w3.org/dpub/IG/wiki/Tables_1#Tables_1 is already discussed in other issues
> Agree with these above
> 
> .
> "User directed styling modifications (font family)" https://www.w3.org/dpub/IG/wiki/UserFontFamilyAdjustments is about customizing the font used by RS/UA.
> Evaluation: consolidate to describe the mecanics of browser/RS/publisher CSS?
> 
> I think this falls under the general UC of personalization. That _is_, in my view, an important UC
