### ISSUE TITLE
Clarifying a use case in the OWP section

### ISSUE THREAD

**Issue by hlflanagan** [w3c/dpub-pwp-ucr#70]
This needs to be turned into one or more use cases:
"Educational materials are increasingly making use of OWP facilities. They include runnable program snippets, interactive testing tools (linked to online evaluation facilities); in many respect, the borderline between these publications and web applications is becoming fuzzy."

**Comment by iherman** [comment]
Closing this issue, because the discussion on the same issue happens on #95
