### ISSUE TITLE
Defining what needs to be archived

### ISSUE THREAD

**Issue by hlflanagan** [w3c/dpub-pwp-ucr#71]
http://w3c.github.io/dpub-pwp-ucr/#manifest_links

Do we need to clarify who gets to define what needs to be archived?

"An archival service wants to harvest (spider) a PWP, and expects to find in the manifest what it will need to make sure it gets all the pieces of the PWP that need to be archived, even if on separate servers."

**Comment by iherman** [comment]
@hlflanagan: I am not sure. It does get into the gritty-nitty details of what needs to be archived, etc. To be worked out, for sure, but may not be relevant for this document.

However, it may be worth emphasizing that this use case also links to the essential-non-essential problem. Ie, the following code snippet may be added to the end of the item:

> Note that this use case is also related to `<a href="#r_essential" class="req-ref-full"></a>`.

**Comment by TzviyaSiegman** [comment]
I don't think this is too nitty gritty. Maybe @iherman  meant to refer to archiving use case?

**Comment by iherman** [comment]
What I meant is: what this text essentially boils down to is that a manifest should express what is an essential resource and what is not (that notion is referred to in that other requirement). How the archival service uses this information is probably beyond the scope of this document.

That being said, referring to the archival use cases, too, is a good idea.

**Comment by lrosenthol** [comment]
agree with @iherman the manifest is a good **hint** to a processor as to how to handle archiving.  But it just that - a hint.  It's up to the archiving processor what to do...

**Comment by iherman** [comment]
Related to #126

**Comment by nullhandle** [comment]
The function of the manifest for archiving should align with the needs of other clients, to indicate the totality and location of the full set of resources that constitute the publication. A more robust manifest architecture would additionally include standards-based provisions for updates (e.g., via [ResourceSync](https://www.openarchives.org/rs/toc)), as [described in the document](https://w3c.github.io/dpub-pwp-ucr/index.html#archiving).

**Comment by lrosenthol** [comment]
I think my clean up in [branch](https://github.com/w3c/dpub-pwp-ucr/tree/dedupe) sets up the alignment of resources, manifests and archiving. @iherman and @nullhandle let me know!

**Comment by iherman** [comment]
@lrosenthol I am fine with what you did
