### ISSUE TITLE
Contradictory requirements in handling online vs offline states?

### ISSUE THREAD

**Issue by hlflanagan** [w3c/dpub-pwp-ucr#72]
“The same content of the PWP should be accessible offline, if circumstances so dictate, without the necessity for the reader to take any particular, technical actions.” -- http://w3c.github.io/dpub-pwp-ucr/#r_onloffl
Vs. 
“This way, when changing the state of a PWP from, e.g., online to offline, an implementation knows which PWP resources are essential for the display of the content, and therefore must be included in the offline version, or which may be skipped” -- http://w3c.github.io/dpub-pwp-ucr/#r_essential

This suggests the content may vary depending on whether the resource is online or offline, and later suggests that the reader may exercise control on whether or not to download and so make available components of the PWP offline (a technical action).

**Comment by bjdmeest** [comment]
'the same content' is probably ambiguous. The point is that a user will be able to retrieve the same information whether he/she is online or offline. So in an offline scenario, a publication about typography will need all fonts embedded to get the message across, whilst for a novel only the HTML contents should suffice (igoring edge cases here). So for a novel, a fallback to system fonts is done without the necessity for the reader to take any particular, technical actions.
All this to make clear that there are use cases that need a notion 'essential resources' that can be publication-specific (e.g., fonts are usually non-essential, but can be made essential for typography publications).

Suggestion (but not sure about the wording myself):
“It should be possible for every PWP to get its message across offline, if circumstances so dictate, without the necessity for the reader to take any particular, technical actions.”
“This way, when changing the state of a PWP from, e.g., online to offline, each PWP can make the distinction (configurable by the author/publisher) between resources that are essential for conveying its message, and therefore must be included in the offline version by an implementation, and which resources may be skipped”

**Comment by lrosenthol** [comment]
This is all cleaned up in the latest drafts
