### ISSUE TITLE
Clarifying the goal of a use case - Privacy or Transitions?

### ISSUE THREAD

**Issue by hlflanagan** [w3c/dpub-pwp-ucr#74]
Is this use case about privacy, or is it about smooth transitions? (Note this was heavily modified in the revised text, but the question remains.)
OLD:
Many publications—especially long form fiction and non-fiction—that users engage with for many hours. During this time, the user may shift states in many ways—starting consumption on an internet enabled PC, moving to an internet enabled portable device, going into offline-mode on that device, and then back to the PC. Ensuring a smooth transition also means that bookmarks, current reading position, etc, are stored, without the need of a central server that may lead to privacy concerns. 

REVISED: 
Klaas is reading an in-depth biography of Catherine the Great. As this is a lengthy document, it takes Klaas several weeks to finish reading the material. During this time, Klaas frequently alternates between reading on his portable device, which may or may not have been online, and reading on his desktop. Ensuring a smooth transition also means that bookmarks, current reading position, personal notes, and more, are stored without the need of a central server that may lead to privacy concerns.

-- http://w3c.github.io/dpub-pwp-ucr/#r_statetrans

**Comment by TzviyaSiegman** [comment]
I recommend removing the comment about privacy for the sake of clarity. This is fundamentally about transitions.

**Comment by lrosenthol** [comment]
I actually removed the entire use case in [branch](https://github.com/w3c/dpub-pwp-ucr/tree/dedupe) since we are no longer talking about states either.
