### ISSUE TITLE
When is a PWP a single document, or a number of documents?

### ISSUE THREAD

**Issue by hlflanagan** [w3c/dpub-pwp-ucr#75]
Does this requirement:
“User agents must treat a PWP, regardless of the number of components, as a single unit as opposed to individual documents.” -- http://w3c.github.io/dpub-pwp-ucr/#r_single

contradict this requirement: 
“A PWP will likely be composed of multiple web documents. A more complicated PWP may have many more components, meaning that extracting in advance all the references to other constituent resources may be prohibitive. It is therefore necessary for the reading system to have an easy access to the list of constituent resources, and some of their characteristics like their media types or sizes.” http://w3c.github.io/dpub-pwp-ucr/#r_con-res

and this one:
"In order to make serial publications lighter and speed up processing, a PWP should support the injection of external resources." -- http://w3c.github.io/dpub-pwp-ucr/#r_extreshttp://w3c.github.io/dpub-pwp-ucr/#r_extres

The interpretation seems to be "treat a PWP as a single unit, except when you don't because some might material might be optional, or be external resources."

**Comment by iherman** [comment]
This is (now) related to issues #107, #99

**Comment by TzviyaSiegman** [comment]
Is this a contradiction? I think we are asking for the treatment of multiple documents as one. We should clean up the point about injection of external resources.

**Comment by iherman** [comment]
I do not think we should touch the document right now, let the reorganization take place. That being said, I am not sure there is a contradiction... What we say is something like
1. A Web Publication is a collection of a number of individual Web Resources
2. A Web Publication must have its own URL representing that collection
3. A Web Publication is not a hermetically closed thing, and it may also refer to other Web Resources that are not part of the Web Publication
4. For handling of a Web Publication, the resources that are part of the WP should be known, eg, declaratively.

We will have to clarify the text, but I am hesitant to do it now, while the reorg takes place.

**Comment by pkra** [comment]
@iherman just checking: a Web Publication can include other Web Publications?

**Comment by iherman** [comment]
I have never given a more extensive thought, but my first gut reaction is to say 'yes'. I am not sure, however, what it would mean for the implementation when handling WP-s; there may be some obstacles.

**Comment by pkra** [comment]
Thanks, Ivan. I feel the same actually.

**Comment by lrosenthol** [comment]
Peter - absolutely!  I actually mentioned this on my slide at TPAC.

**Comment by lrosenthol** [comment]
I am pretty sure that this is cleaned up pretty well in [branch](https://github.com/w3c/dpub-pwp-ucr/tree/dedupe).  I didn't touch the top line definition of PWP, however...

**Comment by iherman** [comment]
I believe #157, the newly reorganized version, etc, covers this better.
