### ISSUE TITLE
Default for content

### ISSUE THREAD

**Issue by hlflanagan** [w3c/dpub-pwp-ucr#76]
In the division of essential versus non-essential, what should be considered the default if the content is not tagged one way or the other?

**Comment by iherman** [comment]
I guess essential... (but I am not sure this is something for the UCR document)

**Comment by bjdmeest** [comment]
I agree with Ivan, probably essential default, but I wouldn't go into technical details just yet :)

**Comment by lrosenthol** [comment]
I decided not to deal with the details (as suggested by @bjdmeest).  Too early at this point.
I did, however, do a bunch of cleanup on the essential/non-essential stuff
