### ISSUE TITLE
Essential versus non-essential and fonts

### ISSUE THREAD

**Issue by hlflanagan** [w3c/dpub-pwp-ucr#77]
Do we need to consider how, when personalizing a document, a reading system will differentiate between a user-described "necessary" font versus one chosen for aesthetic purposes only?

 "A font used for aesthetic purposes only in display of a book may not be essential and an implementation may decide not to embed it for offline use" http://w3c.github.io/dpub-pwp-ucr/#r_essential

**Comment by iherman** [comment]
The "how" is not really something to be described here. see also #107

**Comment by lrosenthol** [comment]
I removed this use case in [branch](https://github.com/w3c/dpub-pwp-ucr/tree/dedupe)
