### ISSUE TITLE
Defining terms

### ISSUE THREAD

**Issue by hlflanagan** [w3c/dpub-pwp-ucr#78]
It would be helpful if we had a clear definition of the following terms. They are sometimes (but not always) used interchangeably within the doc. If we can consolidate, and then add definitions to the terminology section to be clear, that would improve the doc.

Publication
Resource
Instance (see Identifiers)
Component (see Archiving)
Rendition
Version

**Comment by iherman** [comment]
+1; add to the terminology section

Also: Reading System (per #117)

**Comment by iherman** [comment]
There is a (shorter) terminology section in #157 now.
