### ISSUE TITLE
Unique identification to be moved to Fundamental?

### ISSUE THREAD

**Issue by hlflanagan** [w3c/dpub-pwp-ucr#82]
If this requirement is "essential" should it be moved into the Fundamentals section?
"A unique identification of a specific publication, regardless of whether it is online or offline, or whether it is part of a web site or a single (packaged) file is essential. This unique identification should be mapped onto the “real” location of the publication smoothly, without requiring the author’s interaction. " -- http://w3c.github.io/dpub-pwp-ucr/#r_uniq-id-state

**Comment by iherman** [comment]
I would agree with that

**Comment by TzviyaSiegman** [comment]
@hlflanagan please move when you work on document re-org.

**Comment by iherman** [comment]
Done in #157 (and earlier)
