### ISSUE TITLE
Annotation versus Highlight?

### ISSUE THREAD

**Issue by hlflanagan** [w3c/dpub-pwp-ucr#84]
Is there a reason to use the term "highlights" instead of "annotations" in the use case Why have this note instead of just calling the example in the use case an annotation? If the terms are in fact identical in meaning, we could remove the note and simplify the document (there are no other notes quite like this).

http://w3c.github.io/dpub-pwp-ucr/#r_locator-state

**Comment by iherman** [comment]
The two terms are often used the same way but, often, a highlight is a special form of annotation...
