### ISSUE TITLE
User Agent use cases

### ISSUE THREAD

**Issue by hlflanagan** [w3c/dpub-pwp-ucr#86]
The use cases in http://w3c.github.io/dpub-pwp-ucr/#r_manifest-metadata mostly don't read as use cases; they seem to be additional requirements.

**Comment by sideshowbarker** [comment]
> The use cases in http://w3c.github.io/dpub-pwp-ucr/#r_manifest-metadata mostly don't read as use cases; they seem to be additional requirements.

Pretty clearly none of them are stating anything in terms of actual user (people) needs. They should either be restated in terms of actual user needs, or dropped. And in general the same thing should be done for any other use-case statements in the document that are not describing actual user needs.

**Comment by lrosenthol** [comment]
@sideshowbarker Why do use cases have to have people associated with them? Why can't they be use cases for machine processing or other non-human-based consumption?

**Comment by TzviyaSiegman** [comment]
@sideshowbarker if we re-worded these as "as a publisher, I'm concerned about bandwidth and processing speed...", would you be more comfortable? These are all user agent conformance criteria - is it too soon?

**Comment by sideshowbarker** [comment]
> @sideshowbarker if we re-worded these as "as a publisher, I'm concerned about bandwidth and processing speed..."

Yes I think that would be an improvement

**Comment by lrosenthol** [comment]
Cleaned this section up and moved it out manifests - so it's just about metadata.  See [branch](https://github.com/w3c/dpub-pwp-ucr/tree/dedupe)

**Comment by iherman** [comment]
It is now in the main branch; closing
