### ISSUE TITLE
invigorated socio-cultural engagement

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#88]
> New models of economic sustainability, innovative experiences of knowledge and invigorated socio-cultural engagement depend on this.

heh, "invigorated socio-cultural engagement"... it's gets a little hyperbolic. Maybe drop this?

**Comment by atyposh** [comment]
Any suggestions on alternative text? Or should we just drop it altogether?

**Comment by TzviyaSiegman** [comment]
I vote to drop. We dropped similar text from the WP spec.
