### ISSUE TITLE
online/offline

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#90]
> The terms “online” and “offline” are used in this document, but the borderline between these is not always clear cut.

These are fairly well defined concepts on the Web Platform, particularly as reflected in through the fetch spec and `navigator.onLine`. I don't think this document should discuss online/offline, particularly as it makes things more confusing.

**Comment by sideshowbarker** [comment]
I think “offline” has a lot of relevance for actual users.

Users know that there are times when they are offline: For example, if they are flying on an airplane for some number of hours without Wifi or any other connection to the Internet.

I agree that our technical specs should better reference the terminology in the Fetch spec (and Service Workers spec) around caching, etc.

But given that this is a use-cases-and-requirements document, I think it should instead always be trying to present the use cases from the user point of view.

**Comment by marcoscaceres** [comment]
Agree. Perhaps the text can be revised to express more closely @sideshowbarker's comment (i.e., define it in what it means to users)... it might already do that, I can't remember anymore.

**Comment by TzviyaSiegman** [comment]
This document presents use cases and requirements for a variety of users, not just readers. @sideshowbarker can you recommend some more Fetch- and Service Worker-oriented language? I like the recommendation.

**Comment by TzviyaSiegman** [comment]
Document reconstructed. "Offline" is addressed in http://w3c.github.io/dpub-pwp-ucr/index.html#fundamental-offline and in http://w3c.github.io/dpub-pwp-ucr/index.html#pwp. To propose language associate Fetch and SW, please open new issues.
