### ISSUE TITLE
OWP is uncommon

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#92]
Referring to the platform as "OWP" is not common in the community. Maybe just say "Web Platform" instead?

**Comment by iherman** [comment]
I must admit I am torn between this and the official W3C terminology using "OWP"... The charter of the IG, for example, refers to OWP.

Maybe an addition to the terminology section?

**Comment by marcoscaceres** [comment]
Odd, I've never seen OWP... gotta stop hanging out with those WHATWG kids.

**Comment by iherman** [comment]
:-) Yes, it is the official W3C term. We can discuss whether it is optimal or not, but that is another discussion...

(Is it o.k. if I close this issue?)

**Comment by sideshowbarker** [comment]
I also do not like the use of “OWP” and I do not use it myself. It’s unnecessary abbreviation that is not widely understood outside of the W3C; instead we should be using either “Web platform” or these days, better yet “the Web runtime”.
