### ISSUE TITLE
Some very antiquated terminology

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#94]
There seems to be some very antiquated terminology and assumptions made about the web: 

> facilities 

We commonly call those "features", and more recently "powerful features" (for features that require user permissions).  

> formidable development of visualization systems

Are you referring to the use of WebGL? It might be better to be more explicit about precisely what technology you are talking about here... otherwise it sounds, um, more "magical" than it actually is. 

> runnable program snippets, 

You mean JavaScript?

**Comment by marcoscaceres** [comment]
> or Java

hehe... god no! :)

**Comment by marcoscaceres** [comment]
> User agent must be able to give value counters (page counters, section numbering, footnotes, endnotes) across the PWP (as opposed to individual components being numbered separately)

This presupposes that that mode of finding things (page counters, etc.) within a text is optimum. It may turn out to be flawed and sub-optimal (see Kindle's hopeless attempt at this). Given developer and UX/UI folks the ability to create new means of finding/referencing things in texts and collections of texts is far superior.

**Comment by TzviyaSiegman** [comment]
@marcoscaceres Thanks for the feedback. We know that page counters seem clumsy and archaic, but in the experience of the publishing world, readers really like them. I used to be a big advocate of generated locators based on id or fuzzy anchoring, but readers complain. They want page numbers.

**Comment by iherman** [comment]
@marcoscaceres : I agree that section needs reformulation to make it less magical (b.t.w, I believe the reference was as much for WebGL as for libraries like d3).

@TzviyaSiegman @marcoscaceres : I maybe old-skool, but when I read a (digital) book and I use pagination, I definitely like to have the page number around, it gives me another visual clue or where I am in the book. Ie, a continuous page number is important...

**Comment by BillKasdorf** [comment]
Plus they are essential for accessibility when the authoritative version of a publication is paginated, and when things like cross references, indexes, and citations in the literature cite those page numbers. It's not a matter of just liking them, it's a matter of needing them.

**Comment by iherman** [comment]
Proposed solution:

> Req. 2: PWPs should be able to make use of all facilities offered by the OWP.
> 
> There is a formidable development of visualization systems, interactive tools, and other powerful facilities that are built on top of the OWP, including accessing external services like Wolfram Alfa. These tools have been traditionally developed for browsers, and provide possibilities that traditional publications, such as books, magazines, scholarly papers, and educational materials, should also benefit from. That requires publications to become first class citizens on the web platform.

Rewritten to:

> Req. 2: PWPs should be able to make use of all features offered by the OWP.
> 
> There is a remarkable development of tools and frameworks built on top of OWP that make it possible to develop powerful interactive layers on top of OWP. These include, for example, data visualization systems (e.g., d3, built on top of SVG), or possibilities to access external services like Wolfram Alfa. These tools have been traditionally developed for browsers, and provide possibilities that traditional publications, such as books, magazines, scholarly papers, and educational materials, should also benefit from. That requires publications to become first class citizens on the web platform.

Also, the second use case in the same section, ie,:

> Educational materials are increasingly making use of OWP facilities. They include runnable program snippets, interactive testing tools (linked to online evaluation facilities); in many respects, the borderline between these publications and web applications is becoming fuzzy.

Rewritten to:

> Educational publications are increasingly making use of OWP features. They include JavaScript based interactive testing tools (possibly linked to online evaluation facilities), visualization of data or of algorithms, built-in interpreters for various languages (e.g., for courses on programming); in many respects, the borderline between these publications and web applications is becoming fuzzy.

Cc: @hlflanagan

**Comment by marcoscaceres** [comment]
s/javascript based interactive testing tools/javascript-based interactive testing tools

By "testing tools", do you mean like exams for students? Otherwise, I'm confusing it with software testing tools? 

Otherwise, 👍 from me.

**Comment by iherman** [comment]
@marcoscaceres yes, I meant testing tools for students. Is there a better word for it?

**Comment by marcoscaceres** [comment]
Maybe just "They include interactive exams" and drop the JS-based part.

**Comment by iherman** [comment]
@hlflanagan just cc-ing this again to flag marcos' last proposal

**Comment by iherman** [comment]
Done in the [separate editorial branch](https://github.com/w3c/dpub-pwp-ucr/blob/pwp-ucr-editorial1/index.html).
