### ISSUE TITLE
Odd statement is odd...

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#95]
> Educational materials are increasingly making use of OWP facilities. They include runnable program snippets, interactive testing tools (linked to online evaluation facilities); in many respect, the borderline between these publications and web applications is becoming fuzzy.

this seems really odd and has some strange underlying assumptions: if the "educational material" is already on the Web, it's already part of the Web (there is no "borderline" that this was once a different publication type).

**Comment by marcoscaceres** [comment]
Also, the "use case" above doesn't follow the format used in the other use cases: where, for example, there is a clear actor (e.g., "Bob", or  "BigBoxCo"). 

Additionally, we've been putting educational material on the Web for 25+ years - with educational institutions being the early adopters of the Web. Are we really pretending that this is some kind of new trend?

**Comment by iherman** [comment]
Related to issue #70 

Cc: @hlflanagan

**Comment by sideshowbarker** [comment]
> Additionally, we've been putting educational material on the Web for 25+ years - with educational institutions being the early adopters of the Web. Are we really pretending that this is some kind of new trend?

Yes, I think many people reading this document are going to ask pretty much that same question.

> if the "educational material" is already on the Web, it's already part of the Web (there is no "borderline" that this was once a different publication type).

Yeah I don‘t think readers of this document are going to see any existing “borderline” here at all.

But I think the broader problem might be that the requirement stated in this section is not necessary:

> Req. 2: PWPs should be able to make use of all facilities offered by the OWP

We would not say “Web documents should be able to make use of all facilities offered by the OWP”. And all of the use cases presented in this document can be addressed by just using Web documents and existing features of the Web runtime. So I think this entire section could be removed.

**Comment by TzviyaSiegman** [comment]
@marcoscaceres @sideshowbarker Is current wording OK? Please close issue if you're comfortable with it.
