### ISSUE TITLE
flexboxes

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#96]
> Susan uses CSS, images, flexboxes, and

Flexbox is CSS... there are also no such thing as "flexboxes" AFAIK.

**Comment by marcoscaceres** [comment]
Maybe you mean?:
Susan uses a flexible CSS layout, that includes images...

**Comment by iherman** [comment]
Agreed.

Proposed solution: reformulate per [Marcos' comment](https://github.com/w3c/dpub-pwp-ucr/issues/96#issuecomment-246884908)

Cc: @hlflanagan

**Comment by iherman** [comment]
Done in the [separate editorial branch](https://github.com/w3c/dpub-pwp-ucr/blob/pwp-ucr-editorial1/index.html).
