### ISSUE TITLE
Duplicate use cases

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#97]
These two appear to be the same use case: 

> Ann reads the War and Peace which, when printed, is over 1200 pages. In order to have a better sense of her progress in the book and to make navigation within the book easier (i.e., to support usability) she decides to switch her reading environment to paged view.
> 
> Fatima wants to choose between a scrolled view and a paginated view of content that extends across multiple HTML documents.

**Comment by iherman** [comment]
I would agree.

Proposed solution: remove the use case with Fatima.

Cc: @hlflanagan

**Comment by iherman** [comment]
Done in the [separate editorial branch](https://github.com/w3c/dpub-pwp-ucr/blob/pwp-ucr-editorial1/index.html).
